<?php

session_start();

include_once '../php/portal/portal.php';

\Portal\Maintenance::handleUserPortal();

\Portal\PortalAccessVerification::verifyAccess();

$database = new \Users\Database();

$seats = array();

if(isset($_SESSION['worldcreator_manager_email']) && isset($_SESSION['worldcreator_manager_password']))
{
    $account = $database->selectAccountByEmailAndPassword($_SESSION["worldcreator_manager_email"], $_SESSION["worldcreator_manager_password"]);

    $seats = $database->selectUsersByAccountId($account->id);
}
else
{
    $seat = $database->selectUserByEmailAndPassword($_SESSION["worldcreator_user_email"], $_SESSION["worldcreator_user_password"]);

    array_push($seats, $seat);
}


?>

<!DOCTYPE html>
<html class="dark bg-color-dark-scale-5"
      lang="en">
<head>
    <?php
    \Portal\Utility::writeMetaData('World Creator - Customer Portal', 'The customer portal seat management page.','', 'en');
    ?>

    <!-- Favicon -->
    <link rel="shortcut icon"
          href="../img/favicon.png"
          type="image/x-icon"/>
    <link rel="apple-touch-icon"
          href="../img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link id="googleFonts"
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light%7CPlayfair+Display:400&display=swap"
          rel="stylesheet"
          type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet"
          href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="../vendor/fontawesome-pro-6.3.0-web/css/all.min.css">
    <link rel="stylesheet"
          href="../vendor/animate/animate.compat.css">
    <link rel="stylesheet"
          href="../vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet"
          href="../vendor/magnific-popup/magnific-popup.min.css">
    <link rel="stylesheet"
          href="../vendor/twentytwenty/css/twentytwenty.css">

    <!-- Theme CSS -->
    <link rel="stylesheet"
          href="../css/theme.css">
    <link rel="stylesheet"
          href="../css/theme-elements.css">
    <link rel="stylesheet"
          href="../css/theme-blog.css">
    <link rel="stylesheet"
          href="../css/theme-shop.css">

    <!-- Current Page CSS -->
    <link rel="stylesheet"
          href="../vendor/circle-flip-slideshow/css/component.css">

    <!-- Skin CSS -->
    <link id="skinCSS"
          rel="stylesheet"
          href="../css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet"
          href="../css/custom.css">

    <!-- Head Libs -->
    <script src="../vendor/modernizr/modernizr.min.js"></script>

    <script
            id="fsc-api"
            src="https://d1f8f9xcsvx3ha.cloudfront.net/sbl/0.8.5/fastspring-builder.min.js"
            type="text/javascript"
            data-storefront="bitethebytes.onfastspring.com/popup-company"
            data-data-callback="dataCallbackFunction"> <!--Remove .test-->
    </script>

    <script type="text/javascript">
        window.onload = function ()
        {
            OpenInformation();
        };

        function OpenInformation()
        {
            var element = document.getElementById("info-window");

            if (element)
                $("#info-window").modal('show');
        }

        function dataCallbackFunction(fsdata)
        {
            if (fsdata.tags)
            {
                document.getElementById("key").append(JSON.stringify(fsdata.tags));
            }
        }
    </script>

    <script>
        window.fwSettings = {
            'widget_id': 44000002580
        };
        !function ()
        {
            if ("function" != typeof window.FreshworksWidget)
            {
                var n = function ()
                {
                    n.q.push(arguments)
                };
                n.q = [], window.FreshworksWidget = n
            }
        }()
    </script>

    <script type="text/javascript"
            src="https://widget.freshworks.com/widgets/44000002580.js"
            async=""
            defer=""></script>

</head>
<body data-plugin-page-transition>
<?php
include 'php/gdpr.php';
?>
<div class="body bg-color-dark-scale-5">
    <?php
    include 'php/header.php';
    ?>

    <div role="main"
         class="main">

        <section class="page-header page-header-modern page-header-background page-header-background-md mt-0 mb-0"
                 style="background-image: url(../img/pages/World-Creator-02.webp); height: 50vh;">
            <div class="container text-center z-index-1 h-100">
                <div class="d-flex flex-column align-items-center justify-content-center h-100">
                    <div class="container appear-animation"
                         data-appear-animation="blurIn"
                         data-appear-animation-delay="0"
                         data-plugin-options="{'minWindowWidth': 0}">
                        <div class="row text-center pt-4">
                            <div class="col">
                                <h1 class="text-color-light font-weight-extra-bold text-12 mb-3">
                                    World Creator Seats</h1>
                                <h2 class="text-color-light lead tall text-7">
                                    Associated to your account</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <?php
        include 'php/menu-sub.php';
        ?>

        <?php
        \Portal\MessageResult::handle();
        ?>

        <div class="container pt-4">
            <div class="row">
                <div class="col text-justify">
                    <?php
                    if($seats)
                    {
                        $unassignedSeatsFound = false;
                        foreach($seats as $seat)
                        {
                            if($seat->email == '')
                            {
                                $unassignedSeatsFound = true;
                                break;
                            }
                        }

                        if($unassignedSeatsFound)
                        {
                            echo '  
                                <div class="row process process-shapes process-shapes-hover-animate mt-3 pt-3">                          
								    <div class="process-step col-lg-12 mb-5 mb-lg-4">
									    <div class="process-step-circle">
										    <strong class="process-step-circle-content">!</strong>
									    </div>
									    <div class="process-step-content">
										    <h4 class="mb-1 text-5 font-weight-bold">Unassigned seats found</h4>
										    <p class="mb-0 text-color-grey font-weight-medium">One or more seats are not assigned to a user. Identify the unassigned seat and click the ASSIGN button. A pop-up will appear asking you to enter the user\'s email address. The password is automatically generated and cannot be changed (security policy). Use this seat username and password to log into World Creator.</p>
									    </div>
								    </div>
								</div>';
                        }
                        else
                        {
                            echo '
                                <div class="container pb-3">
                                    <div class="row">
                                        <div class="col text-justify text-color-grey">
                                            Below are all the seats associated with your account. Feel free to view, reassign, reset or renew and upgrade them as needed. For further assistance, we recommend that you read this <a href="https://bitethebytes.freshdesk.com/support/solutions/articles/44002348944-customer-portal#Section%3A-Seat-/-Seats" target="_blank">article</a> which explains seat management in detail. So far everything looks good as there are no unallocated seats listed.                                                 
                                        </div>
                                    </div>
                                </div>';
                        }
                    }
                    else
                    {
                        echo '  
                            <div class="row process process-shapes process-shapes-hover-animate mt-3 pt-3">                          
							    <div class="process-step col-lg-12 mb-5 mb-lg-4">
								    <div class="process-step-circle">
									    <strong class="process-step-circle-content">!</strong>
								    </div>
								    <div class="process-step-content">
									    <h4 class="mb-1 text-5 font-weight-bold">No seats found</h4>
									    <p class="mb-0 text-color-grey font-weight-medium">There are no seats associated with your account. Please contact support@bitethebytes.com.</p>
								    </div>
								</div>
							</div>';
                    }
                    ?>
                </div>
            </div>
        </div>

        <div class="container pt-2 pb-5">
            <?php
            $counter = 0;

            $totalSeats = 0;
            $totalCounter = 0;

            if($seats)
            {
                $totalSeats = count($seats);

                foreach($seats as $seat)
                {
                    $counter += 1;
                    $totalCounter += 1;

                    if($counter == 1)
                    {
                        echo ' <div class="container">                   
                            <div class="row text-center">';
                    }

                    if($totalSeats == 1)
                    {
                        echo '<div class="col-lg-4 pt-2"></div>';
                    }
                    else if($totalSeats == 2 && $totalCounter != $totalSeats)
                    {
                        echo '<div class="col-lg-2 pt-2"></div>';
                    }

                    echo '                    
                        <div class="col-lg-4 pt-2">
                            <div class="card bg-color-dark-scale-2 border-width-1 border-color-hover-primary transition-2ms">
                                <div class="card-body">
                                    <div class="text-center">';

                    if($seat->isPerpetual() && !$seat->isGift() && !$seat->isTrial())
                    {
                        echo '<i class="icon-user icons text-color-success text-8"></i>';
                    } else if($seat->isTrial())
                    {
                        echo '<i class="icon-user icons text-color-secondary text-8"></i>';
                    } else if($seat->isGift())
                    {
                        echo '<i class="icon-user icons text-color-grey text-8"></i>';
                    } else
                    {
                        echo '<i class="icon-user icons text-warning text-8"></i>';
                    }
                    echo '</div>';

                    if($seat->isTrial())
                    {
                        echo '<div class="card-text text-2 text-color-secondary">Trial<br>[limited runtime]</div>';
                    } else if($seat->isGift())
                    {
                        echo '<div class="card-text text-2">Gift<br>[lifetime access]</div>';
                    } else if($seat->isPerpetual())
                    {
                        echo '<div class="card-text text-2 text-color-success">Perpetual<br>[runs forever]</div>';
                    } else if($seat->isSubscriptionMonthly())
                    {
                        echo '<div class="card-text text-2 text-warning">Monthly Subscription ' . ($seat->isSubActive ? '' : '<br>[no auto renew]') . '</div>';
                    } else if($seat->isSubscriptionYearly())
                    {
                        echo '<div class="card-text text-2 text-warning">Yearly Subscription ' . ($seat->isSubActive ? '' : '<br>[no auto renew]') . '</div>';
                    }

                    if($seat->isCasual())
                    {
                        echo '<div class="card-text text-1 pb-3">Casual License</div>';
                    }
                    else if($seat->isProfessional())
                    {
                        echo '<div class="card-text text-1 pb-3">Professional License</div>';
                    }
                    else
                    {
                        echo '<div class="card-text text-1 pb-3">Company License</div>';
                    }

                    if($seat->sku == "WC3PC")
                    {
                        echo '<a onclick="fastspring.builder.tag({\'user_id\':\'' . $seat->id . '\'});" data-fsc-action="Add,Checkout" data-fsc-item-path-value="world-creator-upgrade-casual-to-pro" class="btn btn-xs btn-light btn-rounded btn-modern mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Upgrade to a Professional license">Upgrade Version to Professional</a>';
                    }
                    else if($seat->sku == "WC3PI")
                    {
                        echo '<a onclick="fastspring.builder.tag({\'user_id\':\'' . $seat->id . '\'});" data-fsc-action="Add,Checkout" data-fsc-item-path-value="world-creator-upgrade-pro-to-company" class="btn btn-xs btn-light btn-rounded btn-modern mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Upgrade to a Company license">Upgrade Version to Company</a>';
                    }
                    else
                    {
                        echo '-';
                    }

                    if(!empty($seat->lastSigninDate))
                    {
                        echo '<div class="card-text text-1 pt-3">License successfully activated</div>';
                    } else
                    {
                        echo '<div class="card-text text-1 pt-3">License not yet activated</div>';
                    }

                    echo '<h4 class="card-title mb-1 text-4">' . (empty($seat->email) ? "UNASSIGNED" : $seat->email) . '</h4>';

                    if($seat->isTrial())
                    {
                        echo '<div class="card-text text-2">Received by ' . $seat->store . '</div>';
                        if($seat->isEndDateExpired())
                        {
                            echo '<div class="card-text text-2">Trial ended ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        } else
                        {
                            echo '<div class="card-text text-2">Trial until ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        }
                    } else if($seat->isGift())
                    {
                        echo '<div class="card-text text-2">Gifted by ' . $seat->store . '</div>';
                        echo '<div class="card-text text-2">Lifetime Maintenance</div>';
                    } else if($seat->isPerpetual())
                    {
                        echo '<div class="card-text text-2">Purchased through ' . $seat->store . '</div>';
                        if($seat->isEndDateExpired())
                        {
                            echo '<div class="card-text text-2">Maintenance ended ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        } else
                        {
                            echo '<div class="card-text text-2">Maintenance until ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        }
                    } else if($seat->isSubscriptionMonthly())
                    {
                        echo '<div class="card-text text-2">Purchased through ' . $seat->store . '</div>';
                        if($seat->isEndDateExpired())
                        {
                            echo '<div class="card-text text-2">Monthly Subscription ended ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        } else
                        {
                            echo '<div class="card-text text-2">Monthly Subscription until ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        }
                    } else if($seat->isSubscriptionYearly())
                    {
                        echo '<div class="card-text text-2">Purchased through ' . $seat->store . '</div>';
                        if($seat->isEndDateExpired())
                        {
                            echo '<div class="card-text text-2">Yearly Subscription ended ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        } else
                        {
                            echo '<div class="card-text text-2">Yearly Subscription until ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        }
                    }
                    else if($seat->isRental())
                    {
                        echo '<div class="card-text text-2">Purchased through ' . $seat->store . '</div>';
                        if($seat->isEndDateExpired())
                        {
                            echo '<div class="card-text text-2">Rental period ended ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        } else
                        {
                            echo '<div class="card-text text-2">Rental period until ' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '</div>';
                        }
                    }


                    echo '<div class="row pt-3">';
                    echo '<div class="col-lg-12">';

                    echo '<a href="#form_seat_view_' . $seat->id . '" class="popup-with-form btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="View seat"><i class="fas fa-search"></i></a>';
                    //echo '<a href="#form_seat_download_offline_license_' . $seat->id . '" class="popup-with-form btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1"  data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Download offline License"><i class="fas fa-newspaper"></i></a>';

                    if(isset($_SESSION['worldcreator_manager_email']) && isset($_SESSION['worldcreator_manager_password']))
                    {
                        if($seat->isAssigned())
                        {
                            echo '<a href="#form_seat_unassign_' . $seat->id . '" class="popup-with-form btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Withdraw seat">Withdraw</a>';
                        } else
                        {
                            echo '<a href="#form_seat_assign_' . $seat->id . '" class="popup-with-form btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Assign seat to a new user">Assign</a>';
                        }
                    }

                    echo '<a href="#form_seat_revoke_' . $seat->id . '" class="popup-with-form btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Reset all workstations">Reset</a>';

                    if(isset($_SESSION['worldcreator_manager_email']) && isset($_SESSION['worldcreator_manager_password']))
                    {
                        if($seat->isSubscriptionCancellable())
                        {
                            echo '<a href="#form_seat_cancel_subscription_' . $seat->id . '" class="popup-with-form btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Cancel associated subscription">Cancel</a>';
                        }

                        if($seat->isSubscriptionRenewable())
                        {
                            echo '<a href="#form_seat_renew_subscription_' . $seat->id . '" class="popup-with-form btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Resume canceled subscription">RESUME</a>';
                        }

                        if($seat->isMaintenanceRenewable())
                        {
                            switch($seat->sku)
                            {
                                case "WC3PI":
                                    echo '<a onclick="fastspring.builder.tag({\'user_id\':\'' . $seat->id . '\'});" data-fsc-action="Add,Checkout" data-fsc-item-path-value="world-creator-maintenance-indie" class="btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Renew associated maintenance plan">Renew</a>';
                                    break;

                                case "WC3PC":
                                    echo '<a onclick="fastspring.builder.tag({\'user_id\':\'' . $seat->id . '\'});" data-fsc-action="Add,Checkout" data-fsc-item-path-value="world-creator-maintenance-casual" class="btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Renew associated maintenance plan">Renew</a>';
                                    break;

                                case "WC3PS":
                                    echo '<a onclick="fastspring.builder.tag({\'user_id\':\'' . $seat->id . '\'});" data-fsc-action="Add,Checkout" data-fsc-item-path-value="world-creator-maintenance-small" class="btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Renew associated maintenance plan">Renew</a>';
                                    break;

                                case "WC3PL":
                                    echo '<a onclick="fastspring.builder.tag({\'user_id\':\'' . $seat->id . '\'});" data-fsc-action="Add,Checkout" data-fsc-item-path-value="world-creator-maintenance-enterprise" class="btn btn-xs btn-primary-scale-2 btn-modern btn-rounded mr-1" data-bs-toggle="tooltip" data-bs-animation="false" data-bs-placement="bottom" title="Renew associated maintenance plan">Renew</a>';
                                    break;
                            }
                        }
                    }

                    echo '</div></div>';

                    echo '<div class="pt-2 text-center"><a class="text-2 text-color-grey" href="https://bitethebytes.freshdesk.com/support/solutions/articles/44002348944-customer-portal#Section%3A-Seat-/-Seats" target="_blank">Need help?</a></div>';

                    echo '</div></div></div>';

                    if($totalSeats == 1)
                    {
                        echo '<div class="col-lg-4 pt-2"></div>';
                    }
                    else if($totalSeats == 2 && $totalCounter == $totalSeats)
                    {
                        echo '<div class="col-lg-2 pt-2"></div>';
                    }

                    if($counter == 3)
                    {
                        $counter = 0;
                        echo ' </div></div>';
                    }

                    if($totalCounter == $totalSeats && (($totalCounter % 3) != 0))
                    {
                        echo ' </div></div>';
                    }

                    echo '
                        <form id="form_seat_view_' . $seat->id . '"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action=""
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <h4>View Seat</h4>
                                </div>
                            </div>
                            
                            <div class="form-row mt-2 text-justify">
                                <div class="col-lg-12">
                                    <p class="mb-4">Below you will see your seat information. Please contact your World Creator Account Manager if you would like to change your settings.</p>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col">                                    
                                    <input type="text"
                                           class="form-control text-color-light"                                           
                                           value="' . $seat->id . '"
                                           readonly hidden>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col">
                                    <label>License</label>
                                    <input type="text"
                                           class="form-control text-color-light"                                           
                                           value="' . ($seat->isCasual()?'Casual':($seat->isProfessional()?'Professional':'Company')) . '"
                                           readonly>
                                </div>
                            </div>
                                                        
                            <div class="form-row">
                                <div class="form-group col-lg-6">
                                    <label>Email</label>
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           value="' . $seat->email . '"
                                           readonly>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Password</label>
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           value="' . \Portal\Utility::decrypt($seat->password) . '"
                                           readonly>
                                </div>
                            </div>';

                    if($seat->isSubscription())
                    {
                        echo '<div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>Model</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="' . $seat->getModelType() . '"
                                       readonly>
                            </div>
                            <div class="form-group col-lg-6">
                                <label>Status</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="' . ($seat->isSubActive ? 'Active' : 'Cancelled') . '"
                                       readonly>
                            </div>
                          </div>
                          
                          <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>Subscription Creation Date</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->creationDate)) . '"
                                       readonly>
                            </div>
                            <div class="form-group col-lg-6">
                                <label>Subscription End Date</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '"
                                       readonly>
                            </div>
                          </div>';
                    }

                    if($seat->isPerpetual())
                    {
                        echo '<div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>Model</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="' . $seat->getModelType() . '"
                                       readonly>
                            </div>                            
                            <div class="form-group col-lg-6">
                                <label>Maintenance End Date</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '"
                                       readonly>
                            </div>                          
                          </div>';
                    }

                    if($seat->isTrial())
                    {
                        echo '<div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>Model</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="Trial"
                                       readonly>
                            </div>                            
                            <div class="form-group col-lg-6">
                                <label>Maintenance End Date</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="' . date("M j, Y", \Portal\Utility::dotNetTicksToDateTime($seat->endDate)) . '"
                                       readonly>
                            </div>                          
                          </div>';
                    }

                    if($seat->isGift())
                    {
                        echo '<div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>Model</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="Gift"
                                       readonly>
                            </div>                            
                            <div class="form-group col-lg-6">
                                <label>Maintenance End Date</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       value="Lifetime Maintenance"
                                       readonly>
                            </div>                          
                          </div>';
                    }

                    if($seat->isWorkstation01Set())
                    {
                        echo '
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <label>Workstation 1</label>
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           value="' . $seat->workstationId1 . '"
                                           readonly>
                                </div>                           
                            </div>';
                    }

                    if($seat->isWorkstation02Set())
                    {
                        echo '
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <label>Workstation 2</label>
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           value="' . $seat->workstationId2 . '"
                                           readonly>
                                </div>                          
                            </div>';
                    }

                    echo '                            
                            <div class="form-row pt-3">
                                <div class="col-sm-12 text-center">
                                    <button type="submit" class="btn btn-rounded btn-modern btn-primary">OK</button>                                    
                                </div>
                            </div>
                        </form>
                            ';

                    /*
                    echo '
                        <form id="form_seat_download_offline_license_' . $seat->id . '"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action="../php/portal/users/seat_download_license.php"
                              method="post"
                              target="_blank"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <h4>Download Offline License</h4>
                                </div>
                            </div>
                            
                            <div class="form-row">
                            <div class="form-group col-lg-12">
                                <label>Seat ID</label>
                                <input type="text"
                                       class="form-control text-color-light"
                                       name="id"
                                       value="' . $seat->id . '"
                                       readonly>
                            </div>
                        </div>
                    
                            <div class="form-row mt-2 text-center">
                                <div class="col-lg-12">
                                    <p class="mb-4">Do you really want to download the offline license file for user <b>' . $seat->email . '</b>?</p>
                                </div>
                            </div>
                    
                            <div class="form-row pt-3">
                                <div class="col-sm-12">
                                    <a href="' . basename($_SERVER["PHP_SELF"]) . '">
                                        <button type="button"
                                                class="btn btn-primary btn-rounded btn-modern float-left">No
                                        </button>
                                    </a>
                                    <button type="submit" name="submit" value="' . basename($_SERVER["PHP_SELF"]) . '" class="btn btn-rounded btn-modern btn-primary float-right">Yes</button>
                                </div>
                            </div>
                        </form>
                        ';
                    */

                    echo '
                        <form id="form_seat_assign_' . $seat->id . '"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action="../php/portal/users/seat_assign.php"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <h4>Assign Seat</h4>
                                </div>
                            </div>
                            
                            <div class="form-row mt-2 text-justify">
                                <div class="col-lg-12">
                                    <p class="mb-4">Assigning a seat means that you are assigning a user to that seat, specified by an email and password (auto-generated). You can then give the login details to the user to activate and run World Creator.</p>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <input type="text"
                                           class="form-control text-color-light"
                                           name="id"
                                           value="' . $seat->id . '"
                                           readonly hidden>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-6">
                                    <label>Email</label>
                                    <input type="email"
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           name="email"
                                           placeholder="Email"
                                           value=""
                                           required>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Password</label>
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           name="password"
                                           placeholder="Password"
                                           value="' . \Portal\Utility::generateRandomString() . '"
                                           readonly>
                                </div>
                            </div>
                    
                            <div class="form-row pt-3">
                                <div class="col-sm-12">
                                    <a href="' . basename($_SERVER["PHP_SELF"]) . '">
                                        <button type="button"
                                                class="btn btn-primary btn-rounded btn-modern float-left">Cancel
                                        </button>
                                        </a>
                                        <button type="submit" name="submit" value="' . basename($_SERVER["PHP_SELF"]) . '" class="btn btn-rounded btn-modern btn-primary float-right">Submit</button>
                                    </div>
                                </div>
                            </form>
                            ';

                    echo '
                        <form id="form_seat_unassign_' . $seat->id . '"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action="../php/portal/users/seat_unassign.php"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <h4>Withdraw Seat</h4>
                                </div>
                            </div>
                            
                            <div class="form-row mt-2 text-justify">
                                <div class="col-lg-12">
                                    <p class="mb-4">Withdrawing a seat licence means that the current assignment to a user is deleted and the seat can be reassigned to another user. This deletes the e-mail and password as well as all associated workstations.</p>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-12">                                    
                                    <input type="text"
                                           class="form-control text-color-light"
                                           name="id"
                                           value="' . $seat->id . '"
                                           readonly hidden>
                                </div>
                            </div>
                    
                            <div class="form-row mt-2 text-center">
                                <div class="col-lg-12">
                                    <p class="mb-4">Do you really want to withdraw this seat?</p>
                                </div>
                            </div>
                    
                            <div class="form-row pt-3">
                                <div class="col-sm-12">
                                    <a href="' . basename($_SERVER["PHP_SELF"]) . '">
                                        <button type="button"
                                                class="btn btn-primary btn-rounded btn-modern float-left">No
                                        </button>
                                        </a>
                                        <button type="submit" name="submit" value="' . basename($_SERVER["PHP_SELF"]) . '" class="btn btn-rounded btn-modern btn-primary float-right">Yes</button>
                                    </div>
                                </div>
                            </form>
                            ';

                    echo '
                        <form id="form_seat_cancel_subscription_' . $seat->id . '"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action="../php/portal/users/seat_cancel_subscription.php"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <h4>Cancel Subscription</h4>
                                </div>
                            </div>
                            
                            <div class="form-row mt-2 text-justify">
                                <div class="col-lg-12">
                                    <p class="mb-4">Cancelling a subscription for a seat means that you are stopping the automatic payment for World Creator. Please note that World Creator will no longer function once the subscription has expired. You will need to renew the subscription in order for World Creator to work again.</p>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-12">                                    
                                    <input type="text"
                                           class="form-control text-color-light"
                                           name="id"
                                           value="' . $seat->id . '"
                                           readonly hidden>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <label>Reference</label>
                                    <input type="text"
                                           class="form-control text-color-light"
                                           name="reference"
                                           value="' . $seat->reference . '"
                                           >
                                </div>
                            </div>
                    
                            <div class="form-row mt-2 text-center">
                                <div class="col-lg-12">
                                    <p class="mb-4">Do you really want to canel the subscription for this seat?</p>
                                </div>
                            </div>
                    
                            <div class="form-row pt-3">
                                <div class="col-sm-12">
                                    <a href="' . basename($_SERVER["PHP_SELF"]) . '">
                                        <button type="button"
                                                class="btn btn-primary btn-rounded btn-modern float-left">No
                                        </button>
                                        </a>
                                        <button type="submit" name="submit" value="' . basename($_SERVER["PHP_SELF"]) . '" class="btn btn-rounded btn-modern btn-primary float-right">Yes</button>
                                    </div>
                                </div>
                            </form>
                            ';

                    echo '
                        <form id="form_seat_renew_subscription_' . $seat->id . '"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action="../php/portal/users/seat_renew_subscription.php"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <h4>Renew Subscription</h4>
                                </div>
                            </div>
                            
                            <div class="form-row mt-2 text-justify">
                                <div class="col-lg-12">
                                    <p class="mb-4">Renewing a subscription for a seat means that you will resume automatic payment for World Creator and will be able to access the World Creator application again.</p>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-12">                                    
                                    <input type="text"
                                           class="form-control text-color-light"
                                           name="id"
                                           value="' . $seat->id . '"
                                           readonly hidden>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <label>Reference</label>
                                    <input type="text"
                                           class="form-control text-color-light"
                                           name="reference"
                                           value="' . $seat->reference . '"
                                           >
                                </div>
                            </div>
                    
                            <div class="form-row mt-2 text-center">
                                <div class="col-lg-12">
                                    <p class="mb-4">Do you really want to renew the subscription for this seat?</p>
                                </div>
                            </div>
                    
                            <div class="form-row pt-3">
                                <div class="col-sm-12">
                                    <a href="' . basename($_SERVER["PHP_SELF"]) . '">
                                        <button type="button"
                                                class="btn btn-primary btn-rounded btn-modern float-left">No
                                        </button>
                                        </a>
                                        <button type="submit" name="submit" value="' . basename($_SERVER["PHP_SELF"]) . '" class="btn btn-rounded btn-modern btn-primary float-right">Yes</button>
                                    </div>
                                </div>
                            </form>
                            ';

                    echo '
                        <form id="form_seat_renew_maintenance_' . $seat->id . '"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action="../php/portal/users/seat_renew_subscription.php"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <h4>Renew Maintenance</h4>
                                </div>
                            </div>
                            
                            <div class="form-row mt-2 text-justify">
                                <div class="col-lg-12">
                                    <p class="mb-4">Renewing a seat means that you are purchasing a maintenance plan for World Creator. This allows you to download the latest version of the World Creator application for a set period of time (usually 12 months).</p>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-12">                                    
                                    <input type="text"
                                           class="form-control text-color-light"
                                           name="id"
                                           value="' . $seat->id . '"
                                           readonly hidden>
                                </div>
                            </div>
                    
                            <div class="form-row mt-2 text-center">
                                <div class="col-lg-12">
                                    <p class="mb-4">Do you really want to purchase a Maintenance Plan for this seat?</p>
                                </div>
                            </div>
                    
                            <div class="form-row pt-3">
                                <div class="col-sm-12">
                                    <a href="' . basename($_SERVER["PHP_SELF"]) . '">
                                        <button type="button"
                                                class="btn btn-primary btn-rounded btn-modern float-left">No
                                        </button>
                                        </a>
                                        <button type="submit" name="submit" value="' . basename($_SERVER["PHP_SELF"]) . '" class="btn btn-rounded btn-modern btn-primary float-right">Yes</button>
                                    </div>
                                </div>
                            </form>
                            ';

                    echo '
                        <form id="form_seat_revoke_' . $seat->id . '"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action="../php/portal/users/seat_revoke.php"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <h4>Reset Workstations</h4>
                                </div>
                            </div>
                            
                            <div class="form-row mt-2 text-justify">
                                <div class="col-lg-12">
                                    <p class="mb-4">Resetting the workstations means that World Creator can be activated on two other computers. This cancels the previous activations.</p>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-lg-12">                                    
                                    <input type="text"
                                           class="form-control text-color-light"
                                           name="id"
                                           value="' . $seat->id . '"
                                           readonly hidden>
                                </div>
                            </div>
                    
                            <div class="form-row mt-2 text-center">
                                <div class="col-lg-12">
                                    <p class="mb-4">Do you really want to reset all workstations for this seat?</p>
                                </div>
                            </div>
                    
                            <div class="form-row pt-3">
                                <div class="col-sm-12">
                                    <a href="' . basename($_SERVER["PHP_SELF"]) . '">
                                        <button type="button"
                                                class="btn btn-primary btn-rounded btn-modern float-left">No
                                        </button>
                                        </a>
                                        <button type="submit" name="submit" value="' . basename($_SERVER["PHP_SELF"]) . '" class="btn btn-rounded btn-modern btn-primary float-right">Yes</button>
                                    </div>
                                </div>
                            </form>
                            ';
                }
            }
            ?>
        </div>
    </div>

    <footer id="footer" class="bg-color-dark-scale-5">
        <?php
        include 'php/footer.php';
        ?>
    </footer>
</div>

<!-- Vendor -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="../vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="../vendor/jquery.cookie/jquery.cookie.min.js"></script>
<script src="../vendor/popper/umd/popper.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../vendor/jquery.validation/jquery.validate.min.js"></script>
<script src="../vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="../vendor/jquery.gmap/jquery.gmap.min.js"></script>
<script src="../vendor/lazysizes/lazysizes.min.js"></script>
<script src="../vendor/isotope/jquery.isotope.min.js"></script>
<script src="../vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="../vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="../vendor/vide/jquery.vide.min.js"></script>
<script src="../vendor/vivus/vivus.min.js"></script>
<script src="../vendor/twentytwenty/js/jquery.event.move.js"></script>
<script src="../vendor/twentytwenty/js/jquery.twentytwenty.js"></script>

<!-- Current Page Vendor and Views -->
<script src="../vendor/circle-flip-slideshow/js/jquery.flipshow.min.js"></script>
<script src="../js/views/view.home.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="../js/theme.js"></script>

<!-- Theme Custom -->
<script src="../js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="../js/theme.init.js"></script>

<!-- Examples -->
<script src="../js/examples/examples.lightboxes.js"></script>

</body>
</html>