<?php

session_start();

include_once '../php/portal/portal.php';

\Portal\Maintenance::handle();

?>
<!DOCTYPE html>
<html class="dark bg-color-dark-scale-5"
      lang="en">
<head>
    <!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=AW-1015744886 "></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-1015744886'); </script>

    <!-- Clarity tracking code for https://www.world-creator.com/ -->
    <script type="text/javascript">
        (function(c,l,a,r,i,t,y){
            c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
            t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
            y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
        })(window, document, "clarity", "script", "ltec5sffsx");
    </script>

    <?php
    \Portal\Utility::writeMetaData('', '','','en');
    ?>

    <!-- Favicon -->
    <link rel="shortcut icon"
          href="../img/favicon.png"
          type="image/x-icon"/>
    <link rel="apple-touch-icon"
          href="../img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link id="googleFonts"
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light%7CPlayfair+Display:400&display=swap"
          rel="stylesheet"
          type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet"
          href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="../vendor/fontawesome-free/css/all.min.css">
    <link rel="stylesheet"
          href="../vendor/animate/animate.compat.css">
    <link rel="stylesheet"
          href="../vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet"
          href="../vendor/magnific-popup/magnific-popup.min.css">
    <link rel="stylesheet"
          href="../vendor/twentytwenty/css/twentytwenty.css">

    <!-- Theme CSS -->
    <link rel="stylesheet"
          href="../css/theme.css">
    <link rel="stylesheet"
          href="../css/theme-elements.css">
    <link rel="stylesheet"
          href="../css/theme-blog.css">
    <link rel="stylesheet"
          href="../css/theme-shop.css">

    <!-- Current Page CSS -->
    <link rel="stylesheet"
          href="../vendor/circle-flip-slideshow/css/component.css">

    <!-- Skin CSS -->
    <link id="skinCSS"
          rel="stylesheet"
          href="../css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet"
          href="../css/custom.css">

    <!-- Head Libs -->
    <script src="../vendor/modernizr/modernizr.min.js"></script>

    <script
            id="fsc-api"
            src="https://d1f8f9xcsvx3ha.cloudfront.net/sbl/0.8.5/fastspring-builder.min.js"
            type="text/javascript"
            data-storefront="bitethebytes.onfastspring.com/popup-company">
    </script>

    <!--
    <script
            id="fsc-api"
            src="https://d1f8f9xcsvx3ha.cloudfront.net/sbl/0.8.5/fastspring-builder.min.js"
            type="text/javascript"
            data-storefront="bitethebytes.test.onfastspring.com/popup-company">
    </script>
    -->

    <script>
        window.fwSettings = {
            'widget_id': 44000002580
        };
        !function ()
        {
            if ("function" != typeof window.FreshworksWidget)
            {
                var n = function ()
                {
                    n.q.push(arguments)
                };
                n.q = [], window.FreshworksWidget = n
            }
        }()

        window.onload = function ()
        {
            OpenInformation();
        };

        function OpenInformation()
        {
            var shown = sessionStorage.getItem('alreadyShow');

            if (shown != "shown")
            {
                $("#info-window").modal('show');
                sessionStorage.setItem('alreadyShow', 'shown');
            }
        }
    </script>
    <script type="text/javascript"
            src="https://widget.freshworks.com/widgets/44000002580.js"
            async=""
            defer=""></script>

</head>

<body class="loading-overlay-showing"
      data-loading-overlay
      data-plugin-options="{'hideDelay': 500, 'effect': 'percentageProgress1'}">
<div class="loading-overlay loading-overlay-percentage bg-color-dark-scale-5">
    <div class="page-loader-progress-wrapper">
        <span class="page-loader-progress text-color-light">0</span>
        <span class="page-loader-progress-symbol text-color-light">%</span>
    </div>
</div>

<?php
include 'php/gdpr.php';
?>

<div class="body bg-color-dark-scale-5">
    <?php
    include 'php/header.php';
    ?>

    <div role="main" class="main pb-5">

        <?php

        if(!isset($_SERVER['HTTP_USER_AGENT']))
        {
            echo '<section class="section border-0 m-0" data-video-path="video/Trailer_03.mp4" data-plugin-video-background style="height: 100vh">';
        } else
        {
            $browserName = \Portal\Utility::getBrowser($_SERVER['HTTP_USER_AGENT']);

            if($browserName == 'Safari')
            {
                echo '
                        <section class="section border-0 m-0"
                                 style="background-image: url(../img/pages/World-Creator-01.webp); 
                                 background-size: cover; 
                                 background-position: center; 
                                 height: 100vh;">';
            } else
            {
                echo '
                        <section class="section border-0 m-0"
                                 data-video-path="video/Trailer_03.mp4"
                                 data-plugin-video-background
                                 style="height: 100vh">';
            }
        }

        ?>
        <div class="container text-center z-index-1 h-100">
            <div class="d-flex flex-column align-items-center justify-content-center h-100">
                <p class="text-12 line-height-1 font-weight-bold text-color-light appear-animation"
                   data-appear-animation="fadeInDownShorter"
                   data-plugin-options="{'minWindowWidth': 0}">GET INSTANT ACCESS TO</p>
                <p class="text-15 mb-5 line-height-1 font-weight-extra-bold text-color-light appear-animation"
                   data-appear-animation="blurIn"
                   data-plugin-options="{'minWindowWidth': 0}"
                   data-appear-animation-delay="300">WORLD CREATOR</p>
                <p class="text-10 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                   data-appear-animation="blurIn"
                   data-plugin-options="{'minWindowWidth': 0}"
                   data-appear-animation-delay="500">Start creating amazing terrains now</p>
                <a href="#main"
                   class="btn btn-rounded btn-primary btn-modern font-weight-bold text-3 py-3 btn-px-5 mt-2 appear-animation"
                   data-hash
                   data-hash-offset="40"
                   data-appear-animation="fadeInUpShorter"
                   data-appear-animation-delay="700"
                   data-appear-animation-duration="1.2s"
                   data-plugin-options="{'minWindowWidth': 0}">PURCHASE NOW</a>
            </div>
            <a href="#main"
               class="slider-scroll-button slider-scroll-button-light position-absolute bottom-10 left-50pct transform3dx-n50"
               data-hash
               data-hash-offset="40"></a>
        </div>

        <?php
        echo '</section>';
        ?>

        <div id="main" class="container bg-color-dark-scale-5">
            <div class="row text-center pt-5">
                <div class="col p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <h3 class="text-transform-none text-14 font-weight-bold line-height-2 pt-5 pb-5">CHOOSE YOUR LICENSE</h3>
                </div>
            </div>
        </div>

        <div class="container bg-color-dark-scale-5">
            <div class="row pt-5 pb-5">
                <div class="col-12 col-lg-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <div class="card border-0 bg-color-dark-scale-2 mt-3">
                        <div class="card-body">
                            <p class="font-weight-bold text-9 text-sm-7 text-xl-9 text-color-light pb-3">CASUAL</p>
                            <p class="card-text text-color-grey pb-2">For hobbyists who are not aiming for commercial use.</p>
                            <ul class="list list-icons">
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-user"></i> 1 Seat / 2 Workstations<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_seat"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-infinity"></i> Perpetual License<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_perpetual"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-paper-plane"></i> Floating License<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_floating"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-globe"></i> 1 Year of Maintenance<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_oneyearofupdates"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-redo"></i> <span class="font-weight-bold">50%</span> for Maintenance Renewal<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_pricingmaintenancerenewal"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-layer-group"></i> Assets<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_samples"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-ticket-alt"></i> Quality Online Support<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_qualitysupport"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-box"></i> Bridge Export and Tools<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_bridge"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-dollar-sign"></i>  <span class="font-weight-bold">No</span> Commercial Use<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_nocommercial"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-cloud-download-alt"></i> <span class="font-weight-bold">No</span> Legacy Downloads<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_nolegacy"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-arrows-alt"></i> <span class="font-weight-bold">Limited</span> Terrain Size<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_limitedexport"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                            </ul>
                            <span class="card-text text-color-grey">* Maximum precision 1 meter</span><br>
                            <span class="card-text text-color-grey">* Windows only</span>
                            <p class="pt-5 pb-4">
                                <?php

                                echo '<span class="font-weight-medium text-3 text-sm-4 text-xl-5 text-color-light pt-2">$</span><span class="font-weight-bold text-9 text-sm-7 text-xl-9 text-color-light">' . number_format(\Portal\Sales::getPrice(\Portal\LicenseType::Casual, \Portal\ModelType::Perpetual),0,"","") . '</span>';

                                if(\Portal\Sales::$Sale != \Portal\SaleType::None)
                                {
                                    echo '<span class="price text-4">Save&nbsp;<span class="font-weight-medium text-2">$</span>' . number_format(\Portal\Sales::getSave(\Portal\LicenseType::Casual, \Portal\ModelType::Perpetual),0,"","") . ' /&nbsp;' . \Portal\Sales::getDiscount() . '%</span>';
                                }
                                ?>
                                <br>
                                <span class="text-1 text-color-grey">One time fee</span>
                            </p>
                            <a href="#"
                               class="btn btn-rounded btn-primary btn-modern btn-block text-4"
                               data-fsc-action="Add,Checkout"
                               data-fsc-item-path-value="world-creator-perpetual-standard"><i class="text-color-light fas fa-shopping-cart"></i>BUY</a>
                            <div class="pt-1 text-center"><a class="popup-with-form text-2 text-color-grey" href="#form_requirements">System Requirements</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <div class="card border-0 bg-color-dark-scale-2 mt-3">
                        <div class="card-body">
                            <p class="font-weight-bold text-9 text-sm-7 text-xl-9 text-color-light pb-3">PROFESSIONAL</p>
                            <p class="card-text text-color-grey pb-2">For professionals and businesses with up to 5 employees.</p>
                            <ul class="list list-icons">
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-user"></i> 1 Seat / 2 Workstations<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_seat"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-infinity"></i> Perpetual License<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_perpetual"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-paper-plane"></i> Floating License<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_floating"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-globe"></i> 1 Year of Maintenance<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_oneyearofupdates"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-redo"></i> <span class="font-weight-bold">50%</span> for Maintenance Renewal<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_pricingmaintenancerenewal"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-layer-group"></i> Assets<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_samples"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-ticket-alt"></i> Quality Online Support<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_qualitysupport"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-box"></i> Bridge Export and Tools<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_bridge"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-dollar-sign"></i> Commercial Use<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_commercial"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-cloud-download-alt"></i> Legacy Downloads<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_legacy"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-arrows-alt"></i> Unlimited Terrain Size<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_export"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                            </ul>
                            <span class="card-text text-color-grey">* No limitations</span><br>
                            <span class="card-text text-color-grey">* Windows only</span>
                            <p class="pt-5 pb-4">
                                <?php
                                echo '<span class="font-weight-medium text-3 text-sm-4 text-xl-5 text-color-light">$</span><span class="font-weight-bold text-9 text-sm-7 text-xl-9 text-color-light">' . number_format(\Portal\Sales::getPrice(\Portal\LicenseType::Professional, \Portal\ModelType::Perpetual),0,"","") . '</span>';

                                if(\Portal\Sales::$Sale != \Portal\SaleType::None)
                                {
                                    echo '<span class="price text-4">Save&nbsp;<span class="font-weight-medium text-2">$</span>' . number_format(\Portal\Sales::getSave(\Portal\LicenseType::Professional, \Portal\ModelType::Perpetual),0,"","") . ' /&nbsp;' . \Portal\Sales::getDiscount() . '%</span>';
                                }
                                ?>
                                <br>
                                <span class="text-1 text-color-grey">One time fee</span>
                            </p>
                            <a href="#"
                               class="btn btn-rounded btn-primary btn-modern btn-block text-4"
                               data-fsc-action="Add,Checkout"
                               data-fsc-item-path-value="world-creator-perpetual-indie"><i class="text-color-light fas fa-shopping-cart"></i> BUY</a>
                            <div class="pt-1 text-center"><a class="popup-with-form text-2 text-color-grey" href="#form_requirements">System Requirements</a></div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-4 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <div class="card border-0 bg-color-dark-scale-2 mt-3">
                        <div class="card-body">
                            <p class="font-weight-bold text-9 text-sm-7 text-xl-9 text-color-light pb-3">COMPANY</p>
                            <p class="card-text text-color-grey pb-2">For businesses with more than 5 employees.</p>
                            <ul class="list list-icons">
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-user"></i> 1 Seat / 2 Workstations<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_seat"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <?php
                                    if(\Portal\Sales::$Sale == \Portal\SaleType::None)
                                    {
                                        echo '<li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-certificate"></i> Perpetual or Rental License<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_perpetualorrental"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>';
                                    }
                                    else
                                    {
                                        echo '<li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-infinity"></i> Perpetual License<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_perpetual"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>';
                                    }
                                ?>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-paper-plane"></i> Floating License<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_floating"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-globe"></i> 1 Year of Maintenance<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_oneyearofupdates"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-redo"></i> <span class="font-weight-bold">50%</span> for Maintenance Renewal<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_pricingmaintenancerenewal"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-layer-group"></i> Assets<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_samples"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-ticket-alt"></i> Premium Online Support<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_premiumsupport"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-box"></i> Bridge Export and Tools<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_bridge"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-dollar-sign"></i> Commercial Use<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_commercial"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-cloud-download-alt"></i> Legacy Downloads<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_legacy"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                                <li class="text-color-light font-weight-extra-light text-3"><i class="text-color-light fas fa-arrows-alt"></i> Unlimited Terrain Size<a class="popup-with-form text-2 text-color-grey text-color-hover-primary float-right" href="#form_info_export"><i class="text-color-grey text-color-hover-light fas fa-question-circle"></i></a></li>
                            </ul>
                            <span class="card-text text-color-grey">* No limitations</span><br>
                            <span class="card-text text-color-grey">* Windows only</span><br>
                            <div class="row">
                                <?php
                                    if(\Portal\Sales::$Sale == \Portal\SaleType::None)
                                    {
                                        echo '
                                        <div class="col-6">
                                            <p class="pt-5 pb-4">
                                                <span class="font-weight-medium text-3 text-sm-4 text-xl-5 text-color-light">$</span><span class="font-weight-bold text-9 text-sm-7 text-xl-9 text-color-light">' . number_format(\Portal\Sales::getPrice(\Portal\LicenseType::Company, \Portal\ModelType::Yearly),0,"","") . '</span>
                                                <br>
                                                <span class="text-1 text-color-grey">One year use</span>
                                            </p>
                                            <a href="#"
                                               class="btn btn-rounded btn-primary btn-modern btn-block text-4"
                                               data-fsc-action="Add,Checkout"
                                               data-fsc-item-path-value="world-creator-enterprise-annually"><i class="text-color-light fas fa-shopping-cart"></i> RENT</a>
                                        </div>';

                                        echo '
                                        <div class="col-6">';
                                    }
                                    else
                                    {
                                        echo '
                                        <div class="col">';
                                    }

                                    echo '
                                    <p class="pt-5 pb-4">
                                        <span class="font-weight-medium text-3 text-sm-4 text-xl-5 text-color-light">$</span><span class="font-weight-bold text-9 text-sm-7 text-xl-9 text-color-light">' . number_format(\Portal\Sales::getPrice(\Portal\LicenseType::Company, \Portal\ModelType::Perpetual),0,"","") . '</span>';

                                    if(\Portal\Sales::$Sale != \Portal\SaleType::None)
                                    {
                                    echo '      
                                        <span class="price text-4">Save&nbsp;<span class="font-weight-medium text-2">$</span>' . number_format(\Portal\Sales::getSave(\Portal\LicenseType::Company, \Portal\ModelType::Perpetual),0,"","") . ' /&nbsp;' . \Portal\Sales::getDiscount() . '%</span>';
                                    }
                                    echo '
                                        <br>
                                        <span class="text-1 text-color-grey">One time fee</span>
                                    </p>
                                    <a href="#"
                                       class="btn btn-rounded btn-primary btn-modern btn-block text-4"
                                       data-fsc-action="Add,Checkout"
                                       data-fsc-item-path-value="world-creator-perpetual-enterprise"><i class="text-color-light fas fa-shopping-cart"></i> BUY</a>
                                    </div>';
                                ?>
                            </div>
                            <div class="pt-1 text-center"><a class="popup-with-form text-2 text-color-grey" href="#form_requirements">System Requirements</a></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_seat"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">1 SEAT - 2 WORKSTATIONS</div>
                                <p class="mb-4 text-justify">You get a seat for one user (e.g. yourself) and run World Creator on two different workstations (e.g. home / work).</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_perpetual"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">PERPETUAL LICENSE</div>
                                <p class="mb-4 text-justify">The perpetual licence entitles you to run and use all versions of World Creator to which you are entitled forever. The versions you are entitled to are those released during your active support and maintenance period. When you purchase the perpetual licence, you are entitled to 1 year of updates (support and maintenance period).</p>
                                <p class="mb-4 text-justify">When your support and maintenance period ends, you will no longer be able to update to newer versions, but your licence can be renewed for further updates.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_perpetualorrental"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">PERPETUAL LICENSE</div>
                                <p class="mb-4 text-justify">The perpetual licence entitles you to run and use all versions of World Creator to which you are entitled forever. The versions you are entitled to are those released during your active support and maintenance period. When you purchase the perpetual licence, you are entitled to 1 year of updates (support and maintenance period).</p>
                                <p class="mb-4 text-justify">When your support and maintenance period ends, you will no longer be able to update to newer versions, but your licence can be renewed for further updates.</p>
                            </div>
                        </div>
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">RENTAL LICENSE</div>
                                <p class="mb-4 text-justify">The rental licence entitles you to use World Creator for a period of 1 year. After this 1 year you can no longer run and use World Creator, but your licence can be renewed for further use and updates.</p>
                                <p class="mb-4 text-justify">During your subscription period you will have access to all new updates to World Creator.</p>

                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_oneyearofupdates"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">1 YEAR OF MAINTENANCE</div>
                                <p class="mb-4 text-justify">You are entitled to 1 year of updates (support and maintenance period).</p>
                                <p class="mb-4 text-justify">After your first year of free updates and support, you can purchase an additional 12 months of maintenance via the customer portal. This will give you access to the latest features, fixes and enhancements in World Creator. Whatever happens, your copy will continue to work and you'll always be able to download the version you're entitled to.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_pricingmaintenancerenewal"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">NAINTENANCE RENEWAL PRICING</div>
                                <p class="mb-4 text-justify">After your first year of free updates and support, you can purchase an additional 12 months of maintenance via the customer portal. Pricing is around <b>50%</b> of the listed license price. This will give you access to the latest features, fixes and enhancements in World Creator. Whatever happens, your copy will continue to work and you'll always be able to download the version you're entitled to.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_samples"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">ASSETS, PRESETS AND SAMPLES</div>
                                <p class="mb-4 text-justify">With your purchase, you get access to 138 royalty-free textures and Adobe Substance materials, plus tons of World Creator presets and samples, ready to use in your own creations and projects.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_floating"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">FLOATING LICENSE</div>
                                <p class="mb-4 text-justify">World Creator allows you to change the user of a purchased seat at any time. It also allows you to manage multiple users via the customer portal, which is ideal for businesses and educational institutions.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_qualitysupport"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">QUALITY ONLINE SUPPORT</div>
                                <p class="mb-4 text-justify">Our high-quality online support, managed by our own developers, is available Monday to Friday (10am CET to 6pm CET - Berlin time).</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_premiumsupport"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">PREMIUM ONLINE SUPPORT</div>
                                <p class="mb-4 text-justify">Our premium online support, managed by our core developers, is available Monday to Sunday (10am CET to 10pm CET - Berlin time).</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_bridge"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">BRIDGE EXPORT AND  TOOLS</div>
                                <p class="mb-4 text-justify">The Bridge Tools are used to quickly port your terrain from World Creator as-is to any of the applications listed below with a single click.</p>
                            </div>
                        </div>
                        <div class="row mt-4 text-center">
                            <div class="col-lg-4">
                                <img class="img-fluid rounded-circle mb-1"
                                     src="../img/logos/applications/blender.webp"
                                     width="32"
                                     height="32"
                                     alt="Blender">
                                <p>Blender</p>
                            </div>
                            <div class="col-lg-4">
                                <img class="img-fluid rounded-circle mb-1"
                                     src="../img/logos/applications/cinema4d.webp"
                                     width="32"
                                     height="32"
                                     alt="Cinema 4D">
                                <p>Cinema 4D</p>
                            </div>
                            <div class="col-lg-4">
                                <img class="img-fluid rounded-circle mb-1"
                                     src="../img/logos/applications/houdini.webp"
                                     width="32"
                                     height="32"
                                     alt="Houdini">
                                <p>Houdini</p>
                            </div>
                        </div>
                        <div class="row mt-4 text-center">
                            <div class="col-lg-6">
                                <img class="img-fluid rounded-circle mb-1"
                                     src="../img/logos/engines/unity.webp"
                                     width="32"
                                     height="32"
                                     alt="Unity Engine">
                                <p>Unity Engine</p>
                            </div>
                            <div class="col-lg-6">
                                <img class="img-fluid rounded-circle mb-1"
                                     src="../img/logos/engines/unreal.webp"
                                     width="32"
                                     height="32"
                                     alt="Unreal Engine">
                                <p>Unreal Engine</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_nocommercial"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">NO COMMERCIAL USE</div>
                                <p class="mb-4 text-justify">You are <b>NOT</b> permitted to use World Creator and/or any data created with World Creator and/or any material / sample assets downloaded from our server(s) for any commercial purpose.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_commercial"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">COMMERCIAL USE</div>
                                <p class="mb-4 text-justify">You are entitled to make commercial use of World Creator and/or any data created with World Creator and/or any material/sample asset downloaded from our server(s).</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_nolegacy"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">NO LEGACY DOWNLOADS</div>
                                <p class="mb-4 text-center">You will <b>NOT</b> have access to older versions of World Creator.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_legacy"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">LEGACY DOWNLOADS</div>
                                <p class="mb-4 text-center">You will have access to older versions of World Creator.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_limitedexport"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">LIMITED TERRAIN SIZE AND PRECISION</div>
                                <p class="mb-4 text-justify">The terrain size is limited to a maximum of 4096 x 4096 pixels with an accuracy of 1 metre.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_info_export"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col">
                                <div class="text-6 text-color-light text-center font-weight-bold pb-4">UNLIMITED TERRAIN SIZE AND PRECISION</div>
                                <p class="mb-4 text-center">There are no limits to the size and precision of the terrain.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <form id="form_requirements"
                          class="white-popup-block mfp-hide bg-color-dark"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2">
                            <div class="col-6">
                                <div class="text-6 text-color-light font-weight-bold pb-4">MINIMUM</div>
                                <ul class="list list-icons">
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> Windows 7 (64 bit)</li>
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> 4th Gen. i5 or equivalent AMD CPU</li>
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> NVidia 1080 with 8GB VRAM or equivalent AMD GPU</li>
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> 8 GB System RAM</li>
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> 2 GB disk space</li>
                                </ul>
                            </div>
                            <div class="col-6">
                                <div class="text-6 text-color-light font-weight-bold pb-4">RECOMMENDED</div>
                                <ul class="list list-icons">
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> Windows 8.1 and above (64 bit)</li>
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> 6th Gen. i7 or equivalent AMD CPU</li>
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> NVidia 3080 with 12GB VRAM or equivalent AMD GPU</li>
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> 16 GB System RAM</li>
                                    <li class="text-color-light font-weight-lighter text-2"><i class="fas fa-check"></i> 2 GB disk space</li>
                                </ul>
                            </div>
                        </div>
                        <div class="form-row mt-2">
                            <div class="col-sm-12">
                                <p class="mb-4 text-justify">We strongly recommend that you do not run World Creator with on-board GPUs enabled. World Creator will not run on a Mac using Parallels for Windows emulation or on Linux using WINE. A Mac build is planned. A Linux build is not planned.</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col-12 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <p class="text-2 text-color text-justify">Prices above are in US Dollars. Prices do not include VAT. If you are within the EU, you will need to provide an EU VAT number to avoid VAT being charged on your payments. Otherwise, VAT will vary depending on the country you are in. The latest version of World Creator is currently available for Windows only. Also, please make sure to read our <a href="eula.phtml">EULA</a>, and <a href="refund_policy.phtml">Refund Policy</a>, before purchasing World Creator.</p>
                    <p class="text-2 text-justify text-color font-weight-semibold">IMPORTANT NOTE: Virtual credit cards are accepted, but it may take up to three (3) days for payment to be approved by FastSpring (our shop provider) - this is typically the case for purchases initiated from China.</p>
                </div>
            </div>
        </div>

        <div class="container bg-color-dark-scale-5">
            <div class="row text-center pt-5 pb-5">
                <div class="col p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <h3 class="text-transform-none text-14 font-weight-bold line-height-2 pt-5 pb-2">MAINTENANCE RENEWAL<br>AND UPDATES</h3>
                    <p class="pl-2 pr-2 line-height-4 text-5 text-justify">After your first year of free updates and support, you can purchase an additional 12 months of maintenance via the customer portal. This will give you access to the latest features, fixes and enhancements in World Creator. Whatever happens, your copy will continue to work, and you'll always be able to download the version you're entitled to. Pricing is 50% of the above listed price depending on the license you own.</p>
                </div>
            </div>
        </div>

        <div class="container bg-color-dark-scale-5">
            <div class="row text-center pt-5 pb-5">
                <div class="col p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <h3 class="text-transform-none text-14 font-weight-bold line-height-2 pt-5 pb-2">EDUCATION AND ACADEMIC INSTITUTIONS</h3>
                    <p class="pl-2 pr-2 line-height-4 text-5 text-justify">We are thrilled to offer a 30% discount to all students and teachers, as well as academic and educational institutions! If you are interested in licensing World Creator for your entire class, we can offer even greater discounts. To take advantage of this amazing opportunity, simply fill out our academic discount request form, and we will send you your discount code within just a few hours!</p>
                    <div class="row">
                        <div class="col-2 col-md-4"></div>
                        <div class="col-8 col-md-4">
                            <p class="pt-4"><a class="popup-with-form text-color-light" href="#form_apply_for_academic"><button class="btn btn-block btn-primary btn-modern btn-rounded text-4">GET ACADEMIC DISCOUNT</button></a></p>
                        </div>
                        <div class="col-2 col-md-4"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <form id="form_apply_for_academic"
                              class="white-popup-block mfp-hide bg-color-dark"
                              action="../php/portal/users/applyForAcademicDiscount.php"
                              method="post"
                              enctype="multipart/form-data">
                            <div class="form-row mt-2 text-center">
                                <div class="col-sm-12">
                                    <p class="font-weight-bold text-color-light text-9">GET</p>
                                    <p class="text-color-grey text-7 pb-2">ACADEMIC DISCOUNT</p>
                                </div>
                            </div>

                            <div class="form-row mt-2">
                                <div class="col-sm-12">
                                    <p class="mb-4 text-justify">Please complete and submit the form below. Be sure to upload an image of your student/teacher ID or a written letter clearly stating your current academic status. Once approved, you will receive your personal academic discount code (usually within 24 hours).</p>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-lg-6">
                                    <label>First Name *</label>
                                    <input type="text"
                                           data-msg-required="Please enter your first name."
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           name="firstName"
                                           value=""
                                           required>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label>Last Name *</label>
                                    <input type="text"
                                           data-msg-required="Please enter your last name."
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           name="lastName"
                                           value=""
                                           required>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col">
                                    <label>Role *</label>
                                    <select name="role"
                                            class="form-control h-auto py-2 text-color-light">
                                        <option value="Student">I am a student</option>
                                        <option value="Teacher">I am a teacher</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col">
                                    <label>Email address *</label>
                                    <input type="email"
                                           data-msg-required="Please enter your email address."
                                           data-msg-email="Please enter a valid email address."
                                           autocomplete="off"
                                           maxlength="100"
                                           class="form-control text-color-light"
                                           name="email"
                                           value=""
                                           required>
                                </div>
                            </div>

                            <div class="form-row pt-4">
                                <div class="form-group col">
                                    <label>Solve the calculation below *</label>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-lg-2">
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="2"
                                           class="form-control text-color-light"
                                           name="sum01"
                                            <?php
                                            echo 'value="' .rand(1,9)  .'"';
                                            ?>
                                           readonly>
                                </div>
                                <div class="form-group col-lg-1 text-center">
                                    <label class="text-5 text-color-grey">+</label>
                                </div>
                                <div class="form-group col-lg-2">
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="2"
                                           class="form-control text-color-light"
                                           name="sum02"
                                            <?php
                                            echo 'value="' .rand(1,9)  .'"';
                                            ?>
                                           readonly>
                                </div>
                                <div class="form-group col-lg-1 text-center">
                                    <label class="text-5 text-color-grey">x</label>
                                </div>
                                <div class="form-group col-lg-2">
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="2"
                                           class="form-control text-color-light"
                                           name="mul03"
                                           <?php
                                           echo 'value="' .rand(1,5)  .'"';
                                           ?>
                                           readonly>
                                </div>
                                <div class="form-group col-lg-1  text-center">
                                    <label class="text-5 text-color-grey">=</label>
                                </div>
                                <div class="form-group col-lg-3">
                                    <input type="text"
                                           autocomplete="off"
                                           maxlength="3"
                                           class="form-control text-color-light"
                                           name="result"
                                           required>
                                </div>
                            </div>

                            <div class="form-row pt-4">
                                <div class="form-group col">
                                    <label for="img">Image of academic proof (max. 2 MB) *</label>
                                </div>
                            </div>

                            <div class="form-row pt-4">
                                <div class="form-group col">
                                    <input class="float-right"
                                           type="file"
                                           id="img"
                                           name="imageofacademicproof"
                                           accept="image/*">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col text-center">
                                    <button type="submit"
                                            class="btn btn-modern btn-rounded btn-primary mt-3 float-right">Submit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="container bg-color-dark-scale-5">
            <div class="row text-center pt-5 pb-5">
                <div class="col p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <h3 class="text-transform-none text-14 font-weight-bold line-height-2 pt-5 pb-2">TRIAL FOR COMPANIES</h3>
                    <p class="pl-2 pr-2 line-height-4 text-5 text-justify">Simply click on the button below and fill out the trial access application form. Please note that trial access is only granted to companies, so requests using generic email addresses such as @gmail, @hotmail, @outlook, @yahoo will be ignored. To ensure a speedy response, please use your official company email address.</p>
                    <div class="row">
                        <div class="col-2 col-md-4"></div>
                        <div class="col-8 col-md-4">
                            <p class="pt-4"><a class="popup-with-form text-color-light" href="#form_apply_for_trial"><button class="btn btn-block btn-primary btn-modern btn-rounded text-4">GET TRIAL ACCESS</button></a></p>
                        </div>
                        <div class="col-2 col-md-4"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <form id="form_apply_for_trial"
                          class="white-popup-block mfp-hide bg-color-dark"
                          action="../php/portal/users/applyForTrial.php"
                          method="post"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2 text-center">
                            <div class="col-sm-12">
                                <p class="font-weight-bold text-color-light text-9">GET</p>
                                <p class="text-color-grey text-7 pb-2">TRAIL ACCESS</p>
                            </div>
                        </div>

                        <div class="form-row mt-2">
                            <div class="col-sm-12">
                                <p class="mb-4 text-justify">Please complete and submit the form below. Once approved, you will receive your trial login details (usually within 24 hours).</p>
                                <p class="mb-4 text-center text-light">Generic providers (e.g. hotmail, gmail, free) and HTTP sites will still be rejected!</p>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-12">
                                <label>Company *</label>
                                <input type="text"
                                       data-msg-required="Please enter your companies legal name."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="company"
                                       value=""
                                       required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-12">
                                <label>Company Website (HTTPS only) *</label>
                                <input type="text"
                                       data-msg-required="Please enter your companies website."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="website"
                                       value=""
                                       required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <label>Company Size *</label>
                                <select name="companySize"
                                        class="form-control h-auto py-2 text-color-light"
                                        required>
                                    <option value="Small Company">(Small) Annual revenue under $1M</option>
                                    <option value="Large Company">(Large) Annual revenue above $1M</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>First Name *</label>
                                <input type="text"
                                       data-msg-required="Please enter your first name."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="firstName"
                                       value=""
                                       required>
                            </div>
                            <div class="form-group col-lg-6">
                                <label>Last Name *</label>
                                <input type="text"
                                       data-msg-required="Please enter your last name."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="lastName"
                                       value=""
                                       required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <label>Email Address *</label>
                                <input type="email"
                                       data-msg-required="Please enter your companies email address."
                                       data-msg-email="Please enter a valid email address."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="email"
                                       value=""
                                       required>
                            </div>
                        </div>

                        <div class="form-row pt-4">
                            <div class="form-group col">
                                <label>Solve the calculation below *</label>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-2">
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="2"
                                       class="form-control text-color-light"
                                       name="sum01"
                                    <?php
                                    echo 'value="' .rand(1,9)  .'"';
                                    ?>
                                       readonly>
                            </div>
                            <div class="form-group col-lg-1 text-center">
                                <label class="text-5 text-color-grey">+</label>
                            </div>
                            <div class="form-group col-lg-2">
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="2"
                                       class="form-control text-color-light"
                                       name="sum02"
                                    <?php
                                    echo 'value="' .rand(1,9)  .'"';
                                    ?>
                                       readonly>
                            </div>
                            <div class="form-group col-lg-1 text-center">
                                <label class="text-5 text-color-grey">x</label>
                            </div>
                            <div class="form-group col-lg-2">
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="2"
                                       class="form-control text-color-light"
                                       name="mul03"
                                    <?php
                                    echo 'value="' .rand(1,5)  .'"';
                                    ?>
                                       readonly>
                            </div>
                            <div class="form-group col-lg-1  text-center">
                                <label class="text-5 text-color-grey">=</label>
                            </div>
                            <div class="form-group col-lg-3">
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="3"
                                       class="form-control text-color-light"
                                       name="result"
                                       required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col text-center">
                                <button type="submit"
                                        class="btn btn-modern btn-rounded btn-primary mt-3 float-right">Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="container bg-color-dark-scale-5">
            <div class="row text-center pt-5 pb-5">
                <div class="col p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <h3 class="text-transform-none text-14 font-weight-bold line-height-2 pt-5 pb-2">PROCUREMENT PORTAL ACCESS</h3>
                    <p class="pl-2 pr-2 line-height-4 text-5 text-justify">Whether you're a company, a reseller, or you run your own shop, we've got you covered. Our programme is the perfect place for you to start purchasing World Creator, either for your own use or for your customers. Welcome to our Procurement Programme! With the Procurement Programme, you can place quotes and orders outside of our main store in no time at all. Simply complete the Procurement Application below, and we'll set up your account immediately. Start requesting quotes and placing orders straight away!</p>
                    <div class="row">
                        <div class="col-2 col-md-4"></div>
                        <div class="col-8 col-md-4">
                            <p class="pt-4"><a class="popup-with-form text-color-light" href="#form_become_a_partner"><button class="btn btn-block btn-primary btn-modern btn-rounded text-4">APPLY NOW</button></a></p>
                        </div>
                        <div class="col-2 col-md-4"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <form id="form_become_a_partner"
                          class="white-popup-block mfp-hide bg-color-dark"
                          action="../php/portal/users/applyAsPartner.php"
                          method="post"
                          enctype="multipart/form-data">
                        <div class="form-row mt-2 text-center">
                            <div class="col-sm-12">
                                <p class="font-weight-bold text-color-light text-9">APPLY</p>
                                <p class="text-color-grey text-7 pb-2">PROCUREMENT PROGRAM</p>
                            </div>
                        </div>

                        <div class="form-row mt-2">
                            <div class="col-sm-12">
                                <p class="mb-4 text-justify">Please complete and submit the form below. Once approved by our sales team, you will receive your partner login details by email.</p>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>Company *</label>
                                <input type="text"
                                       data-msg-required="Please enter your companies full legal name."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="company"
                                       value=""
                                       required>
                            </div>
                            <div class="form-group col-lg-6">
                                <label>Company Website *</label>
                                <input type="text"
                                       data-msg-required="Please enter your companies website."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="website"
                                       value=""
                                       required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <label>VAT ID (only if your country is officially part of the European Union)</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="vatid"
                                       value="">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>First Name *</label>
                                <input type="text"
                                       data-msg-required="Please enter your first name."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="firstName"
                                       value=""
                                       required>
                            </div>
                            <div class="form-group col-lg-6">
                                <label>Last Name *</label>
                                <input type="text"
                                       data-msg-required="Please enter your last name."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="lastName"
                                       value=""
                                       required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col">
                                <label>Email Address *</label>
                                <input type="email"
                                       data-msg-required="Please enter your personal company related email address."
                                       data-msg-email="Please enter a valid email address."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="email"
                                       value=""
                                       required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>Address Line 1</label>
                                <input type="text"
                                       data-msg-required="Please enter your companies street address and building number."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="addressline01"
                                       value=""
                                       required>
                            </div>

                            <div class="form-group col-lg-6">
                                <label>Address Line 2</label>
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="addressline02"
                                       value="">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>ZIP</label>
                                <input type="text"
                                       data-msg-required="Please enter your companies city postal code."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="zip"
                                       value=""
                                       required>
                            </div>
                            <div class="form-group col-lg-6">
                                <label>City</label>
                                <input type="text"
                                       data-msg-required="Please enter your companies city name."
                                       autocomplete="off"
                                       maxlength="100"
                                       class="form-control text-color-light"
                                       name="city"
                                       value=""
                                       required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-6">
                                <label>Country *</label>
                                    <select name="country"
                                            class="form-control h-auto py-2 text-color-light">
                                        <option value="Germany">Germany</option>
                                        <option value="Afghanistan">Afghanistan</option>
                                        <option value="Åland Islands">Åland Islands</option>
                                        <option value="Albania">Albania</option>
                                        <option value="Algeria">Algeria</option>
                                        <option value="American Samoa">American Samoa</option>
                                        <option value="Andorra">Andorra</option>
                                        <option value="Angola">Angola</option>
                                        <option value="Anguilla">Anguilla</option>
                                        <option value="Antarctica">Antarctica</option>
                                        <option value="Antigua and Barbuda">Antigua and Barbuda</option>
                                        <option value="Argentina">Argentina</option>
                                        <option value="Armenia">Armenia</option>
                                        <option value="Aruba">Aruba</option>
                                        <option value="Australia">Australia</option>
                                        <option value="Austria">Austria</option>
                                        <option value="Azerbaijan">Azerbaijan</option>
                                        <option value="Bahamas">Bahamas</option>
                                        <option value="Bahrain">Bahrain</option>
                                        <option value="Bangladesh">Bangladesh</option>
                                        <option value="Barbados">Barbados</option>
                                        <option value="Belarus">Belarus</option>
                                        <option value="Belgium">Belgium</option>
                                        <option value="Belize">Belize</option>
                                        <option value="Benin">Benin</option>
                                        <option value="Bermuda">Bermuda</option>
                                        <option value="Bhutan">Bhutan</option>
                                        <option value="Bolivia">Bolivia</option>
                                        <option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
                                        <option value="Botswana">Botswana</option>
                                        <option value="Bouvet Island">Bouvet Island</option>
                                        <option value="Brazil">Brazil</option>
                                        <option value="British Indian Ocean Territory">British Indian Ocean Territory</option>
                                        <option value="Brunei Darussalam">Brunei Darussalam</option>
                                        <option value="Bulgaria">Bulgaria</option>
                                        <option value="Burkina Faso">Burkina Faso</option>
                                        <option value="Burundi">Burundi</option>
                                        <option value="Cambodia">Cambodia</option>
                                        <option value="Cameroon">Cameroon</option>
                                        <option value="Canada">Canada</option>
                                        <option value="Cape Verde">Cape Verde</option>
                                        <option value="Cayman Islands">Cayman Islands</option>
                                        <option value="Central African Republic">Central African Republic</option>
                                        <option value="Chad">Chad</option>
                                        <option value="Chile">Chile</option>
                                        <option value="China">China</option>
                                        <option value="Christmas Island">Christmas Island</option>
                                        <option value="Cocos (Keeling) Islands">Cocos (Keeling) Islands</option>
                                        <option value="Colombia">Colombia</option>
                                        <option value="Comoros">Comoros</option>
                                        <option value="Congo">Congo</option>
                                        <option value="Congo, The Democratic Republic of The">Congo, The Democratic Republic of The</option>
                                        <option value="Cook Islands">Cook Islands</option>
                                        <option value="Costa Rica">Costa Rica</option>
                                        <option value="Cote D'ivoire">Cote D'ivoire</option>
                                        <option value="Croatia">Croatia</option>
                                        <option value="Cuba">Cuba</option>
                                        <option value="Cyprus">Cyprus</option>
                                        <option value="Czech Republic">Czech Republic</option>
                                        <option value="Denmark">Denmark</option>
                                        <option value="Djibouti">Djibouti</option>
                                        <option value="Dominica">Dominica</option>
                                        <option value="Dominican Republic">Dominican Republic</option>
                                        <option value="Ecuador">Ecuador</option>
                                        <option value="Egypt">Egypt</option>
                                        <option value="El Salvador">El Salvador</option>
                                        <option value="Equatorial Guinea">Equatorial Guinea</option>
                                        <option value="Eritrea">Eritrea</option>
                                        <option value="Estonia">Estonia</option>
                                        <option value="Ethiopia">Ethiopia</option>
                                        <option value="Falkland Islands (Malvinas)">Falkland Islands (Malvinas)</option>
                                        <option value="Faroe Islands">Faroe Islands</option>
                                        <option value="Fiji">Fiji</option>
                                        <option value="Finland">Finland</option>
                                        <option value="France">France</option>
                                        <option value="French Guiana">French Guiana</option>
                                        <option value="French Polynesia">French Polynesia</option>
                                        <option value="French Southern Territories">French Southern Territories</option>
                                        <option value="Gabon">Gabon</option>
                                        <option value="Gambia">Gambia</option>
                                        <option value="Georgia">Georgia</option>
                                        <option value="Germany">Germany</option>
                                        <option value="Ghana">Ghana</option>
                                        <option value="Gibraltar">Gibraltar</option>
                                        <option value="Greece">Greece</option>
                                        <option value="Greenland">Greenland</option>
                                        <option value="Grenada">Grenada</option>
                                        <option value="Guadeloupe">Guadeloupe</option>
                                        <option value="Guam">Guam</option>
                                        <option value="Guatemala">Guatemala</option>
                                        <option value="Guernsey">Guernsey</option>
                                        <option value="Guinea">Guinea</option>
                                        <option value="Guinea-bissau">Guinea-bissau</option>
                                        <option value="Guyana">Guyana</option>
                                        <option value="Haiti">Haiti</option>
                                        <option value="Heard Island and Mcdonald Islands">Heard Island and Mcdonald Islands</option>
                                        <option value="Holy See (Vatican City State)">Holy See (Vatican City State)</option>
                                        <option value="Honduras">Honduras</option>
                                        <option value="Hong Kong">Hong Kong</option>
                                        <option value="Hungary">Hungary</option>
                                        <option value="Iceland">Iceland</option>
                                        <option value="India">India</option>
                                        <option value="Indonesia">Indonesia</option>
                                        <option value="Iran, Islamic Republic of">Iran, Islamic Republic of</option>
                                        <option value="Iraq">Iraq</option>
                                        <option value="Ireland">Ireland</option>
                                        <option value="Isle of Man">Isle of Man</option>
                                        <option value="Israel">Israel</option>
                                        <option value="Italy">Italy</option>
                                        <option value="Jamaica">Jamaica</option>
                                        <option value="Japan">Japan</option>
                                        <option value="Jersey">Jersey</option>
                                        <option value="Jordan">Jordan</option>
                                        <option value="Kazakhstan">Kazakhstan</option>
                                        <option value="Kenya">Kenya</option>
                                        <option value="Kiribati">Kiribati</option>
                                        <option value="Korea, Democratic People's Republic of">Korea, Democratic People's Republic of</option>
                                        <option value="Korea, Republic of">Korea, Republic of</option>
                                        <option value="Kuwait">Kuwait</option>
                                        <option value="Kyrgyzstan">Kyrgyzstan</option>
                                        <option value="Lao People's Democratic Republic">Lao People's Democratic Republic</option>
                                        <option value="Latvia">Latvia</option>
                                        <option value="Lebanon">Lebanon</option>
                                        <option value="Lesotho">Lesotho</option>
                                        <option value="Liberia">Liberia</option>
                                        <option value="Libyan Arab Jamahiriya">Libyan Arab Jamahiriya</option>
                                        <option value="Liechtenstein">Liechtenstein</option>
                                        <option value="Lithuania">Lithuania</option>
                                        <option value="Luxembourg">Luxembourg</option>
                                        <option value="Macao">Macao</option>
                                        <option value="Macedonia, The Former Yugoslav Republic of">Macedonia, The Former Yugoslav Republic of</option>
                                        <option value="Madagascar">Madagascar</option>
                                        <option value="Malawi">Malawi</option>
                                        <option value="Malaysia">Malaysia</option>
                                        <option value="Maldives">Maldives</option>
                                        <option value="Mali">Mali</option>
                                        <option value="Malta">Malta</option>
                                        <option value="Marshall Islands">Marshall Islands</option>
                                        <option value="Martinique">Martinique</option>
                                        <option value="Mauritania">Mauritania</option>
                                        <option value="Mauritius">Mauritius</option>
                                        <option value="Mayotte">Mayotte</option>
                                        <option value="Mexico">Mexico</option>
                                        <option value="Micronesia, Federated States of">Micronesia, Federated States of</option>
                                        <option value="Moldova, Republic of">Moldova, Republic of</option>
                                        <option value="Monaco">Monaco</option>
                                        <option value="Mongolia">Mongolia</option>
                                        <option value="Montenegro">Montenegro</option>
                                        <option value="Montserrat">Montserrat</option>
                                        <option value="Morocco">Morocco</option>
                                        <option value="Mozambique">Mozambique</option>
                                        <option value="Myanmar">Myanmar</option>
                                        <option value="Namibia">Namibia</option>
                                        <option value="Nauru">Nauru</option>
                                        <option value="Nepal">Nepal</option>
                                        <option value="Netherlands">Netherlands</option>
                                        <option value="Netherlands Antilles">Netherlands Antilles</option>
                                        <option value="New Caledonia">New Caledonia</option>
                                        <option value="New Zealand">New Zealand</option>
                                        <option value="Nicaragua">Nicaragua</option>
                                        <option value="Niger">Niger</option>
                                        <option value="Nigeria">Nigeria</option>
                                        <option value="Niue">Niue</option>
                                        <option value="Norfolk Island">Norfolk Island</option>
                                        <option value="Northern Mariana Islands">Northern Mariana Islands</option>
                                        <option value="Norway">Norway</option>
                                        <option value="Oman">Oman</option>
                                        <option value="Pakistan">Pakistan</option>
                                        <option value="Palau">Palau</option>
                                        <option value="Palestinian Territory, Occupied">Palestinian Territory, Occupied</option>
                                        <option value="Panama">Panama</option>
                                        <option value="Papua New Guinea">Papua New Guinea</option>
                                        <option value="Paraguay">Paraguay</option>
                                        <option value="Peru">Peru</option>
                                        <option value="Philippines">Philippines</option>
                                        <option value="Pitcairn">Pitcairn</option>
                                        <option value="Poland">Poland</option>
                                        <option value="Portugal">Portugal</option>
                                        <option value="Puerto Rico">Puerto Rico</option>
                                        <option value="Qatar">Qatar</option>
                                        <option value="Reunion">Reunion</option>
                                        <option value="Romania">Romania</option>
                                        <option value="Russian Federation">Russian Federation</option>
                                        <option value="Rwanda">Rwanda</option>
                                        <option value="Saint Helena">Saint Helena</option>
                                        <option value="Saint Kitts and Nevis">Saint Kitts and Nevis</option>
                                        <option value="Saint Lucia">Saint Lucia</option>
                                        <option value="Saint Pierre and Miquelon">Saint Pierre and Miquelon</option>
                                        <option value="Saint Vincent and The Grenadines">Saint Vincent and The Grenadines</option>
                                        <option value="Samoa">Samoa</option>
                                        <option value="San Marino">San Marino</option>
                                        <option value="Sao Tome and Principe">Sao Tome and Principe</option>
                                        <option value="Saudi Arabia">Saudi Arabia</option>
                                        <option value="Senegal">Senegal</option>
                                        <option value="Serbia">Serbia</option>
                                        <option value="Seychelles">Seychelles</option>
                                        <option value="Sierra Leone">Sierra Leone</option>
                                        <option value="Singapore">Singapore</option>
                                        <option value="Slovakia">Slovakia</option>
                                        <option value="Slovenia">Slovenia</option>
                                        <option value="Solomon Islands">Solomon Islands</option>
                                        <option value="Somalia">Somalia</option>
                                        <option value="South Africa">South Africa</option>
                                        <option value="South Georgia and The South Sandwich Islands">South Georgia and The South Sandwich Islands</option>
                                        <option value="Spain">Spain</option>
                                        <option value="Sri Lanka">Sri Lanka</option>
                                        <option value="Sudan">Sudan</option>
                                        <option value="Suriname">Suriname</option>
                                        <option value="Svalbard and Jan Mayen">Svalbard and Jan Mayen</option>
                                        <option value="Swaziland">Swaziland</option>
                                        <option value="Sweden">Sweden</option>
                                        <option value="Switzerland">Switzerland</option>
                                        <option value="Syrian Arab Republic">Syrian Arab Republic</option>
                                        <option value="Taiwan">Taiwan</option>
                                        <option value="Tajikistan">Tajikistan</option>
                                        <option value="Tanzania, United Republic of">Tanzania, United Republic of</option>
                                        <option value="Thailand">Thailand</option>
                                        <option value="Timor-leste">Timor-leste</option>
                                        <option value="Togo">Togo</option>
                                        <option value="Tokelau">Tokelau</option>
                                        <option value="Tonga">Tonga</option>
                                        <option value="Trinidad and Tobago">Trinidad and Tobago</option>
                                        <option value="Tunisia">Tunisia</option>
                                        <option value="Turkey">Turkey</option>
                                        <option value="Turkmenistan">Turkmenistan</option>
                                        <option value="Turks and Caicos Islands">Turks and Caicos Islands</option>
                                        <option value="Tuvalu">Tuvalu</option>
                                        <option value="Uganda">Uganda</option>
                                        <option value="Ukraine">Ukraine</option>
                                        <option value="United Arab Emirates">United Arab Emirates</option>
                                        <option value="United Kingdom">United Kingdom</option>
                                        <option value="United States">United States</option>
                                        <option value="United States Minor Outlying Islands">United States Minor Outlying Islands</option>
                                        <option value="Uruguay">Uruguay</option>
                                        <option value="Uzbekistan">Uzbekistan</option>
                                        <option value="Vanuatu">Vanuatu</option>
                                        <option value="Venezuela">Venezuela</option>
                                        <option value="Viet Nam">Viet Nam</option>
                                        <option value="Virgin Islands, British">Virgin Islands, British</option>
                                        <option value="Virgin Islands, U.S.">Virgin Islands, U.S.</option>
                                        <option value="Wallis and Futuna">Wallis and Futuna</option>
                                        <option value="Western Sahara">Western Sahara</option>
                                        <option value="Yemen">Yemen</option>
                                        <option value="Zambia">Zambia</option>
                                        <option value="Zimbabwe">Zimbabwe</option>
                                    </select>
                            </div>

                            <div class="form-group col-lg-6">
                                <label>Payment Terms *</label>
                                <select name="paymentterms"
                                        class="form-control h-auto py-2 text-color-light">
                                    <option value="14 Days">14 Days</option>
                                    <option value="30 Days">30 Days</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-row pt-4">
                            <div class="form-group col">
                                <label>Solve the calculation below *</label>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-lg-2">
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="2"
                                       class="form-control text-color-light"
                                       name="sum01"
                                    <?php
                                    echo 'value="' .rand(1,9)  .'"';
                                    ?>
                                       readonly>
                            </div>
                            <div class="form-group col-lg-1 text-center">
                                <label class="text-5 text-color-grey">+</label>
                            </div>
                            <div class="form-group col-lg-2">
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="2"
                                       class="form-control text-color-light"
                                       name="sum02"
                                    <?php
                                    echo 'value="' .rand(1,9)  .'"';
                                    ?>
                                       readonly>
                            </div>
                            <div class="form-group col-lg-1 text-center">
                                <label class="text-5 text-color-grey">x</label>
                            </div>
                            <div class="form-group col-lg-2">
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="2"
                                       class="form-control text-color-light"
                                       name="mul03"
                                    <?php
                                    echo 'value="' .rand(1,5)  .'"';
                                    ?>
                                       readonly>
                            </div>
                            <div class="form-group col-lg-1  text-center">
                                <label class="text-5 text-color-grey">=</label>
                            </div>
                            <div class="form-group col-lg-3">
                                <input type="text"
                                       autocomplete="off"
                                       maxlength="3"
                                       class="form-control text-color-light"
                                       name="result">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col text-center">
                                <button type="submit"
                                        class="btn btn-modern btn-rounded btn-primary mt-3 float-right">Submit
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="container bg-color-dark-scale-5">
            <div class="row text-center pt-5 pb-5">
                <div class="col p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <h3 class="text-transform-none text-14 font-weight-bold line-height-2 pt-5 pb-2">YOU'RE IN GREAT COMPANY</h3>
                    <p class="pl-2 pr-2 pb-5 line-height-4 text-5 text-justify">Since November 2017, World Creator has already been adopted by thousands of happy companies and customers to help shape some of the biggest games and movies.</p>
                    <div class="row content-grid-row">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://2k.com/en-US/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/2k.webp"
                                                    alt="2K"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.a52.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/a52.webp"
                                                    alt="a52"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.amazon.com"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/amazon.webp"
                                                    alt="Amazon"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://atlus.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/atlus.webp"
                                                    alt="Atlus"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://avalanchestudios.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/avalanchestudio.webp"
                                                    alt="Avalanche Studios"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://de.bandainamcoent.eu/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/bandainamco.webp"
                                                    alt="Bandai Namco"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.bioware.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/bioware.webp"
                                                    alt="Bioware"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.blizzard.com/de-de/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/blizzard.webp"
                                                    alt="Blizzard"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://bluebyte.ubisoft.com/de/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/bluebyte.webp"
                                                    alt="BlueByte"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.blur.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/blur.webp"
                                                    alt="Blur"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.bluepointgames.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/bluepoint.webp"
                                                    alt="Blue Point Games"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.bossastudios.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/bossastudios.webp"
                                                    alt="Bossa Studio"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.capcom.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/capcom.webp"
                                                    alt="Capcom"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.certainaffinity.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/certain_affinity.webp"
                                                    alt="Certain Affinity"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.cinesite.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/cinesite.webp"
                                                    alt="Cinesite"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.codemasters.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/codemasters.webp"
                                                    alt="Codemasters"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.crytek.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/crytek.webp"
                                                    alt="Crytek"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://cyborn.be/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/cyborn.webp"
                                                    alt="Cyborn"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.cygames.co.jp/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/cygames.webp"
                                                    alt="Cygames"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.daybreakgames.com/home"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/daybreakgames.webp"
                                                    alt="Daybreak Games"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.deck13.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/deck13.webp"
                                                    alt="Deck13"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.dice.se/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/dice.webp"
                                                    alt="DICE"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.digicpictures.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/digipic.webp"
                                                    alt="Digipic"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.digitalextremes.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/digitalextremes.webp"
                                                    alt="Digital Extremes"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.dlr.de/dlr/desktopdefault.aspx/tabid-10002/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/dlr.webp"
                                                    alt="DLR"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.eidosmontreal.com"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/eidos_montreal.webp"
                                                    alt="Eidos Montreal"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.ea.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/ea.webp"
                                                    alt="Electronic Arts"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://falconscreativegroup.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/falconscreativegroup.webp"
                                                    alt="Falcons Creative Group"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://firaxis.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/firaxis.webp"
                                                    alt="Firaxis"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://firesprite.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/firesprite.webp"
                                                    alt="Firesprite"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.frimastudio.com/en/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/frima.webp"
                                                    alt="FRIMA"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.funcom.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/funcom.webp"
                                                    alt="Funcom"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.ghostvfx.com"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/ghost_vfx.webp"
                                                    alt="GHOST VFX"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://hotheadgames.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/hotheadstudio.webp"
                                                    alt="Hothead Studio"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://hybride.com/en"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/hybride.webp"
                                                    alt="Hybride"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://improbable.io/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/improbable.webp"
                                                    alt="Improbable"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://corp.joycity.com"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/joycity.webp"
                                                    alt="Joy City"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.kylotonn.com/en/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/ktracing.webp"
                                                    alt="KT Racing"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.limbic-entertainment.de/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/limbic.webp"
                                                    alt="Limbic"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.liongamelion.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/liongamelion.webp"
                                                    alt="Lion Game Lion"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://mawiunited.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/mawi.webp"
                                                    alt="MAWI"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.meta.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/meta.webp"
                                                    alt="META"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.microsoftstudios.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/microsoft.webp"
                                                    alt="Microsoft"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://us.ncsoft.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/ncsoft.webp"
                                                    alt="NC Soft"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://neocoregames.com/en"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/neocoregames.webp"
                                                    alt="Neocoregames"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <img class="img-fluid"
                                 src="../img/logos/companies/nexon.webp"
                                 alt="Nexon"/>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.paradoxinteractive.com/en/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/paradox_interactive.webp"
                                                    alt="Paradox Interactive"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.perfectworld.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/perfect_world.webp"
                                                    alt="Perfect World"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.piranha-bytes.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/piranhabytes.webp"
                                                    alt="Piranha Bytes"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.playground-games.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/playgroundgames.webp"
                                                    alt="Playgroundgames"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://pocketgems.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/pocketgems.webp"
                                                    alt="Pocket Gems"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.quanticdream.com/en"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/quanticdream.webp"
                                                    alt="Quantic Dream"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.rsvfx.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/rocketscience.webp"
                                                    alt="Rocketscience"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.sae.edu/deu/de"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/sae.webp"
                                                    alt="SAE"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.sega.com"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/sega.webp"
                                                    alt="SEGA"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.sony.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/sony.webp"
                                                    alt="Sony"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.square-enix.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/squareenix.webp"
                                                    alt="Square Eenix"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://styleframe.de/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/styleframe.webp"
                                                    alt="Styleframe"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.sumo-digital.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/sumodigital.webp"
                                                    alt="Sumo Digital"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.take2games.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/take2gaming.webp"
                                                    alt="Take2 Gaming"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.technicolor.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/technicolor.webp"
                                                    alt="Technicolor"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.ttgames.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/telltalegames.webp"
                                                    alt="Telltale Games"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://thqnordic.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/thqnordic.webp"
                                                    alt="THQ Nordic"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.treyarch.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/treyarch.webp"
                                                    alt="Treyarch"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.ubisoft.com/en-us"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/ubisoft.webp"
                                                    alt="Ubisoft"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://unity.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/unity.webp"
                                                    alt="Unity"/></a>
                        </div>
                    </div>
                    <div class="row content-grid-row mt-4">
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.valvesoftware.com/de/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/valve.webp"
                                                    alt="Valve"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://virtuosgames.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/virtuos.webp"
                                                    alt="Virtuos"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.wbgames.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/wbgames.webp"
                                                    alt="WB Games"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.weltenbauer-se.com"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/weltenbauer.webp"
                                                    alt="Weltenbauer"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.xlgames.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/xlgames.webp"
                                                    alt="XL Games"/></a>
                        </div>
                        <div class="content-grid-item col-6 col-sm-4 col-lg-2 text-center">
                            <a href="https://www.zenimax.com/"
                               target="_blank"><img class="img-fluid"
                                                    src="../img/logos/companies/zenimax.webp"
                                                    alt="Zenimax"/></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer id="footer" class="bg-color-dark-scale-5">
        <?php
        include 'php/footer.php';
        ?>
    </footer>
</div>
<!-- Vendor -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="../vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="../vendor/jquery.cookie/jquery.cookie.min.js"></script>
<script src="../vendor/popper/umd/popper.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../vendor/jquery.validation/jquery.validate.min.js"></script>
<script src="../vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="../vendor/jquery.gmap/jquery.gmap.min.js"></script>
<script src="../vendor/lazysizes/lazysizes.min.js"></script>
<script src="../vendor/isotope/jquery.isotope.min.js"></script>
<script src="../vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="../vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="../vendor/vide/jquery.vide.min.js"></script>
<script src="../vendor/vivus/vivus.min.js"></script>
<script src="../vendor/twentytwenty/js/jquery.event.move.js"></script>
<script src="../vendor/twentytwenty/js/jquery.twentytwenty.js"></script>

<!-- Current Page Vendor and Views -->
<script src="../vendor/circle-flip-slideshow/js/jquery.flipshow.min.js"></script>
<script src="../js/views/view.home.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="../js/theme.js"></script>

<!-- Theme Custom -->
<script src="../js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="../js/theme.init.js"></script>

<!-- Examples -->
<script src="../js/examples/examples.lightboxes.js"></script>
</body>
</html>