<?php

include_once '../php/portal/portal.php';

?>

<!DOCTYPE html>
<html class="dark bg-color-dark-scale-5"
      lang="en">
<head>
    <!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=AW-1015744886 "></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-1015744886'); </script>

    <?php
    \Portal\Utility::writeMetaData('', '','','en');
    ?>

    <!-- Favicon -->
    <link rel="shortcut icon"
          href="../img/favicon.png"
          type="image/x-icon"/>
    <link rel="apple-touch-icon"
          href="../img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link id="googleFonts"
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light%7CPlayfair+Display:400&display=swap"
          rel="stylesheet"
          type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet"
          href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="../vendor/fontawesome-free/css/all.min.css">
    <link rel="stylesheet"
          href="../vendor/animate/animate.compat.css">
    <link rel="stylesheet"
          href="../vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet"
          href="../vendor/magnific-popup/magnific-popup.min.css">
    <link rel="stylesheet"
          href="../vendor/twentytwenty/css/twentytwenty.css">

    <!-- Theme CSS -->
    <link rel="stylesheet"
          href="../css/theme.css">
    <link rel="stylesheet"
          href="../css/theme-elements.css">
    <link rel="stylesheet"
          href="../css/theme-blog.css">
    <link rel="stylesheet"
          href="../css/theme-shop.css">

    <!-- Current Page CSS -->
    <link rel="stylesheet"
          href="../vendor/circle-flip-slideshow/css/component.css">

    <!-- Skin CSS -->
    <link id="skinCSS"
          rel="stylesheet"
          href="../css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet"
          href="../css/custom.css">

    <!-- Head Libs -->
    <script src="../vendor/modernizr/modernizr.min.js"></script>

    <script>
        window.fwSettings = {
            'widget_id': 44000002580
        };
        !function ()
        {
            if ("function" != typeof window.FreshworksWidget)
            {
                var n = function ()
                {
                    n.q.push(arguments)
                };
                n.q = [], window.FreshworksWidget = n
            }
        }()
    </script>
    <script type="text/javascript"
            src="https://widget.freshworks.com/widgets/44000002580.js"
            async=""
            defer=""></script>

</head>
<body class="loading-overlay-showing"
      data-loading-overlay
      data-plugin-options="{'hideDelay': 500, 'effect': 'percentageProgress1'}">
<div class="loading-overlay loading-overlay-percentage bg-color-dark-scale-5">
    <div class="page-loader-progress-wrapper">
        <span class="page-loader-progress text-color-light">0</span>
        <span class="page-loader-progress-symbol text-color-light">%</span>
    </div>
</div>

<div class="body bg-color-dark-scale-5">
    <div role="main"
         class="main"
         style="min-height: calc(100vh - 393px);">
        <div class="container pt-5">
            <div class="row mt-5">
                <div class="col text-center">
                    <div class="logo">
                        <a href="index.phtml">
                            <img width="296"
                                 height="60"
                                 src="../img/logos/applications/WorldCreator.webp"
                                 alt="World Creator">
                        </a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <hr class="solid my-5">
                </div>
            </div>
            <div class="row">
                <div class="col text-center">
                    <div class="overflow-hidden mb-2">
                        <h2 class="font-weight-normal text-7 mb-0 appear-animation"
                            data-appear-animation="maskUp">
                            <strong class="font-weight-extra-bold">SOFTWARE-PIRACY DETECTED</strong></h2>
                    </div>
                    <div class="overflow-hidden mb-1">
                        <p class="lead mb-0 appear-animation"
                           data-appear-animation="maskUp"
                           data-appear-animation-delay="200">Gotcha! You are using a cracked version of World Creator.<br>Your IP was tracked.
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <hr class="solid my-5">
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col-lg-4 appear-animation"
                             data-appear-animation="fadeInLeftShorter"
                             data-appear-animation-delay="600">
                            <div class="feature-box">
                                <div class="feature-box-icon">
                                    <i class="far fa-life-ring"></i>
                                </div>
                                <div class="feature-box-info">
                                    <h4 class="text-4 text-uppercase mb-1 font-weight-bold">Whats this about?</h4>
                                    <p class="mb-4">You have downloaded and used a cracked version of World Creator, which is illegal and shows your criminal activity and criminal intentions.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 appear-animation"
                             data-appear-animation="fadeIn"
                             data-appear-animation-delay="400">
                            <div class="feature-box">
                                <div class="feature-box-icon">
                                    <i class="far fa-clock"></i>
                                </div>
                                <div class="feature-box-info">
                                    <h4 class="text-4 text-uppercase mb-1 font-weight-bold">What now?</h4>
                                    <p class="mb-4">Criminal activities are logged by saving the IP and a timestamp, and might have serious legal consequences, especially if you are within the borders of the EU.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 appear-animation"
                             data-appear-animation="fadeInRightShorter"
                             data-appear-animation-delay="600">
                            <div class="feature-box">
                                <div class="feature-box-icon">
                                    <i class="far fa-envelope"></i>
                                </div>
                                <div class="feature-box-info">
                                    <h4 class="text-4 text-uppercase mb-1 font-weight-bold">How to avoid legal consequences?</h4>
                                    <p class="mb-4">We highly suggest you to <a href="buy.phtml" target="_self">purchase</a> a full license of World Creator, and to contact support@bitethebytes.com, so we can delete your logged piracy action(s).</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Vendor -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="../vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="../vendor/jquery.cookie/jquery.cookie.min.js"></script>
<script src="../vendor/popper/umd/popper.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../vendor/jquery.validation/jquery.validate.min.js"></script>
<script src="../vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="../vendor/jquery.gmap/jquery.gmap.min.js"></script>
<script src="../vendor/lazysizes/lazysizes.min.js"></script>
<script src="../vendor/isotope/jquery.isotope.min.js"></script>
<script src="../vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="../vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="../vendor/vide/jquery.vide.min.js"></script>
<script src="../vendor/vivus/vivus.min.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="../js/theme.js"></script>


<!-- Theme Custom -->
<script src="../js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="../js/theme.init.js"></script>

</body>
</html>