<?php

session_start();

include_once '../php/portal/portal.php';

\Portal\Maintenance::handle();

?>
<!DOCTYPE html>
<html class="dark bg-color-dark-scale-5"
      lang="en">
<head>
    <!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=AW-1015744886 "></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-1015744886'); </script>

    <?php
    \Portal\Utility::writeMetaData('', '','','en');
    ?>

    <!-- Favicon -->
    <link rel="shortcut icon"
          href="../img/favicon.png"
          type="image/x-icon"/>
    <link rel="apple-touch-icon"
          href="../img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link id="googleFonts"
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light%7CPlayfair+Display:400&display=swap"
          rel="stylesheet"
          type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet"
          href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="../vendor/fontawesome-free/css/all.min.css">
    <link rel="stylesheet"
          href="../vendor/animate/animate.compat.css">
    <link rel="stylesheet"
          href="../vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet"
          href="../vendor/magnific-popup/magnific-popup.min.css">
    <link rel="stylesheet"
          href="../vendor/twentytwenty/css/twentytwenty.css">

    <!-- Theme CSS -->
    <link rel="stylesheet"
          href="../css/theme.css">
    <link rel="stylesheet"
          href="../css/theme-elements.css">
    <link rel="stylesheet"
          href="../css/theme-blog.css">
    <link rel="stylesheet"
          href="../css/theme-shop.css">

    <!-- Current Page CSS -->
    <link rel="stylesheet"
          href="../vendor/circle-flip-slideshow/css/component.css">

    <!-- Skin CSS -->
    <link id="skinCSS"
          rel="stylesheet"
          href="../css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet"
          href="../css/custom.css">

    <!-- Head Libs -->
    <script src="../vendor/modernizr/modernizr.min.js"></script>

    <script
        id="fsc-api"
        src="https://d1f8f9xcsvx3ha.cloudfront.net/sbl/0.8.5/fastspring-builder.min.js"
        type="text/javascript"
        data-storefront="bitethebytes.onfastspring.com/popup-company">
    </script>

    <script>
        window.fwSettings = {
            'widget_id': 44000002580
        };
        !function ()
        {
            if ("function" != typeof window.FreshworksWidget)
            {
                var n = function ()
                {
                    n.q.push(arguments)
                };
                n.q = [], window.FreshworksWidget = n
            }
        }()

        window.onload = function ()
        {
            OpenInformation();
        };

        function OpenInformation()
        {
            var shown = sessionStorage.getItem('alreadyShow');

            if (shown != "shown")
            {
                $("#info-window").modal('show');
                sessionStorage.setItem('alreadyShow', 'shown');
            }
        }
    </script>
    <script type="text/javascript"
            src="https://widget.freshworks.com/widgets/44000002580.js"
            async=""
            defer=""></script>

</head>

<body class="loading-overlay-showing"
      data-loading-overlay
      data-plugin-options="{'hideDelay': 500, 'effect': 'percentageProgress1'}">
<div class="loading-overlay loading-overlay-percentage bg-color-dark-scale-5">
    <div class="page-loader-progress-wrapper">
        <span class="page-loader-progress text-color-light">0</span>
        <span class="page-loader-progress-symbol text-color-light">%</span>
    </div>
</div>

<?php
include 'php/gdpr.php';
?>

<div class="body bg-color-dark-scale-5">
    <?php
    include 'php/header.php';
    ?>

    <div role="main" class="main pb-5">

        <?php

        if(!isset($_SERVER['HTTP_USER_AGENT']))
        {
            echo '<section class="section border-0 m-0" data-video-path="video/Trailer_02.mp4" data-plugin-video-background style="height: 100vh">';
        } else
        {
            $browserName = \Portal\Utility::getBrowser($_SERVER['HTTP_USER_AGENT']);

            if($browserName == 'Safari')
            {
                echo '
                        <section class="section border-0 m-0"
                                 style="background-image: url(../img/pages/World-Creator-01.webp); 
                                 background-size: cover; 
                                 background-position: center; 
                                 height: 100vh;">';
            } else
            {
                echo '
                        <section class="section border-0 m-0"
                                 data-video-path="video/Trailer_02.mp4"
                                 data-plugin-video-background
                                 style="height: 100vh">';
            }
        }

        ?>
        <div class="container text-center z-index-1 h-100">
            <div class="d-flex flex-column align-items-center justify-content-center h-100">
                <p class="text-12 line-height-1 font-weight-bold text-color-light appear-animation"
                   data-appear-animation="fadeInDownShorter"
                   data-plugin-options="{'minWindowWidth': 0}">BiteTheBytes GmbH</p>
                <p class="text-15 mb-5 line-height-1 font-weight-extra-bold text-color-light appear-animation"
                   data-appear-animation="blurIn"
                   data-plugin-options="{'minWindowWidth': 0}"
                   data-appear-animation-delay="300">PRIVACY POLICY</p>
                <p class="text-6 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                   data-appear-animation="blurIn"
                   data-plugin-options="{'minWindowWidth': 0}"
                   data-appear-animation-delay="500">Last Updated: 3rd September 2023</p>
            </div>
            <a href="#main"
               class="slider-scroll-button slider-scroll-button-light position-absolute bottom-10 left-50pct transform3dx-n50"
               data-hash
               data-hash-offset="67"></a>
        </div>

        <?php
        echo '</section>';
        ?>

        <div id="main" class="container bg-color-dark-scale-5">
            <div class="row pt-5 pb-5">
                <div class="col pl-3 pr-3 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <p class="font-weight-normal text-4 mb-2 text-justify">Protecting your privacy and data is very important to us. This is not only the case since the GDPR / DSGVO, but since the founding of the company. We take great care that only the data necessary for the operation of the business and for the performance of services in connection with our products is stored. In this Privacy Policy, we fully disclose what information we collect, how we use it, and how we handle it.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">1. What does this privacy policy cover?</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">This privacy policy describes how BitetheBytes (also referred to as "we," "us" or "our") will make use of your information in the context of:</p>
                    <ul>
                        <li>BiteTheBytes-Websites</li>
                        <li>Desktop-Apps</li>
                        <li>BiteTheByte’s marketing, sales, and advertising practices</li>
                    </ul>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">2. What information does BiteTheBytes collect about me?</div>

                    <div class="font-weight-normal text-color-light line-height-2 text-7 mb-3 mt-5">2.1. Websites of BiteTheBytes</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">You remain anonymous: During your entire visit to our website, you do not disclose anything about yourself. We do not store any personal information. </p>

                    <div class="font-weight-normal text-color-light line-height-2 text-7 mb-3 mt-5">2.2. BiteTheBytes Customer Support</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">If you contact us for support or other offerings, BiteTheBytes collects information through Freshdesk (which is used by our ticket system) that identifies you. This includes:</p>
                    <ul>
                        <li>Name</li>
                        <li>Email address</li>
                    </ul>

                    <div class="font-weight-normal text-color-light line-height-2 text-7 mb-3 mt-5">2.3. BiteTheBytes App Purchase</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">By clicking on a purchase button on our website, you will be re-directed to our online shopping provider FastSpring who takes care of the purchase process. For that, FastSpring requires you to enter personal data. This includes:</p>
                    <ul>
                        <li>Company (if applicable)</li>
                        <li>Name</li>
                        <li>Address</li>
                        <li>Country</li>
                        <li>Email address</li>
                        <li>VAT ID (if applicable)</li>
                        <li>Registration number (if applicable)</li>
                        <li>Payment / billing information</li>
                    </ul>

                    <div class="font-weight-normal text-color-light line-height-2 text-7 mb-3 mt-5">2.4. BiteTheBytes App Activation</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">After your purchase of a BiteTheBytes app through FastSpring, we will setup your account on our BiteTheBytes License Server. The following personal information is stored:</p>
                    <ul>
                        <li>Email address</li>
                        <li>First name</li>
                        <li>Last name</li>
                        <li>Company name (if applicable)</li>
                    </ul>

                    <p class="font-weight-normal text-4 mb-2">Beside that, the BiteTheBytes License Server is going to create additional data that is connected to your account right after your purchase:</p>
                    <ul>
                        <li>Product</li>
                        <li>Version</li>
                        <li>License</li>
                        <li>Password (created exclusively by us; you can request it at anytime through the BiteTheBytes application you are using)</li>
                        <li>Information whether your account is a perpetual or subscription account</li>
                        <li>Information whether your account is active, or disabled</li>
                        <li>Information about until what date your maintenance plan or subscription is valid</li>
                        <li>Information about when you purchased your license</li>
                        <li>Information about your last sign-in date</li>
                        <li>Information about your workstation IDs (required by license server to prevent abusing activations)</li>
                    </ul>
                    <p class="font-weight-normal text-4 mb-2">Additionally you may enter and store further additional information by signing into your account. That is:</p>
                    <ul>
                        <li>Nickname (displayed on a render that you upload to our public gallery)</li>
                        <li>Information about your social accounts (this is optionally and can only be applied if you have been invited for uploading renders to our public gallery)</li>
                    </ul>

                    <div class="font-weight-normal text-color-light line-height-2 text-7 mb-3 mt-5">2.5. BiteTheBytes App Usage and App Updates</div>
                    <p class="font-weight-normal text-4 mb-2">When you use your BiteTheBytes app or when you install updates to the app, we collect information about:</p>
                    <ul>
                        <li>Your device (hardware ID)</li>
                        <li>Your BiteTheBytes app (email, password, version)</li>
                        <li>Date of last sign in</li>
                    </ul>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">3. How does BiteTheBytes use the information it collects about me?</div>
                    <p class="font-weight-normal text-4 mb-2">BiteTheBytes uses the information we collect about you for the following purposes:</p>
                    <ul>
                        <li>To fulfill a contract, or take steps linked to a contract: this is relevant where you register to use a BiteTheBytes app or website (whether paid, or as a free trial). This includes:</li>

                        <ul>
                            <li>Providing you with the BiteTheBytes websites and apps for which you have registered, and any other services or products that you have requested</li>
                            <li>Verifying your identity</li>
                            <li>Taking payments</li>
                            <li>Sending you necessary communications (for example, related to payments or expiration of your subscription)</li>
                            <li>Providing customer service or support</li>
                        </ul>

                        <li>As required by BiteTheBytes to conduct our business and pursue our legitimate interests, in particular:</li>

                        <ul>
                            <li>Providing you with the BiteTheBytes websites and apps for which you have registered and any other products and services you have requested</li>
                            <li>Diagnosing problems in our apps</li>
                            <li>Investigating and responding to any comments or complaints that you may send us</li>
                            <li>In connection with legal claims, compliance, regulatory and investigative purposes as necessary (including disclosure of information in connection with legal process or litigation)</li>
                        </ul>

                        <li>Where you give BiteTheBytes your consent or otherwise consistent with your choices:</li>

                        <ul>
                            <li>Sending you information about BiteTheBytes products and services, special offers and similar information, and sharing your information with third parties for their own marketing purposes (where your consent is required)</li>
                            <li>Placing cookies and using similar technologies on our websites, on our apps and in email communications, in accordance with our Cookies Policy and the information provided to you when those technologies are used</li>
                            <li>Crash reports</li>
                        </ul>

                        <li>For legal reasons:</li>

                        <ul>
                            <li>Responding to requests by government or law enforcement authorities conducting an investigation</li>
                            <li>To detect, prevent, or otherwise address fraud, security or technical issues and software piracy (e.g., to confirm that software is genuine and properly licensed), helping to protect you as well as BiteTheBytes</li>
                        </ul>
                    </ul>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">4. Does BiteTheBytes share my personal information?</div>
                    <p class="font-weight-normal text-4 mb-2">No, BiteTheBytes is NOT sharing your personal information with others.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">5. Is my personal information displayed anywhere?</div>
                    <p class="font-weight-normal text-4 mb-2">BiteTheBytes apps do not display your personal information.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">There are several places within BiteTheBytes’s websites and apps that BiteTheBytes uses (e.g. Discord) that allow you to post comments, upload pictures, or submit content for others to see. Sometimes you can limit who can see what you share, but there are some places where what you share can be seen by the general public or other users of the app or website. Please be careful when you share your personal information. Do not share anything you wouldn’t want publicly known unless you are sure you are posting it within an app or website that allows you to control who sees what you post.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Please note that when you post messages on certain user forums on our websites and apps that we use, your email address or name and/or profile photo may be included and displayed with your message.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">To remove content you have shared on our websites and apps we use, please use the same app or website feature you used to share the content. If another user invites you to participate in shared viewing, editing, or commenting of content, you may be able to delete your contributions, but usually the user who invited you has full control.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">6. Is my personal information secure?</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">We take technical and organizational precautions to protect your personal information against accidental or intentional manipulation, loss, destruction or access by unauthorized persons and to ensure the protection of your rights and compliance with the applicable data protection regulations of the EU and the Federal Republic of Germany.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">The measures taken are designed to ensure the confidentiality, integrity, availability and resilience of the systems and services related to the processing of your data over time and to restore them quickly in the event of a physical or technical incident. This includes encryption of your data. All information that you enter online is encrypted with at least the SSL technology and only then transmitted.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">As a result, this information can never be viewed by unauthorized third parties. Our data processing and security measures are constantly being improved in line with technological developments. Our employees are of course obliged to confidentiality in writing (data secrecy).</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">7. Where does BiteTheBytes store my personal information?</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Your personal information is stored inside a password protected SQL database. That database is located on a virtual machine (Windows Server 2012) hosted by Host Europe GmbH with location in Germany. The access to that virtual machine and the operating system is also password protected.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">8. Does BiteTheBytes transfer my personal information across national borders?</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Our products are marketed and sold internationally. Through a license server based in Germany, purchased products are activated, validated and updated.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">If you execute one of our applications outside of Germany and log in to the license server for the purpose of activation / validation / updates, your personal data (email address and hardware ID) will be transmitted across national borders to our license server. This data transmission is encrypted and is solely for communication reasons between your BiteTheBytes app and the BiteTheBytes license server.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">9. What rights do I have in respect of my personal information?</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Under the law of some countries, you may have the right to ask us for a copy of your personal information; to correct, delete or restrict (stop any active) processing of your personal information; and to obtain the personal information you provide to us for a contract or with your consent in a structured, machine readable format, and to ask us to share (port) this information to another controller.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">In addition, you can object to the processing of your personal information in some circumstances (in particular, where we don’t have to process the information to meet a contractual or other legal requirement).</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">These rights may be limited, for example, if fulfilling your request would reveal personal information about another person, or if you ask us to delete information which we are required by law to keep or have compelling legitimate interests in keeping (such as fraud prevention purposes).</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">To exercise any of these rights (including deactivating your BiteTheBytes account), you can get in touch with us – or our data protection officer – using the details set out below. Additionally, many of our websites allow you to edit your personal information by accessing the "my account," "my profile," or a similar feature of the website you are using. Likewise, you can delete files or photos you have stored in our websites by logging in and using the deletion functions that are available.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">If you have unresolved concerns, you have the right to report them to an EU or other data protection authority where you live, work or where you believe a potential violation may have occurred.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">To use some BiteTheBytes websites, apps, products or services, the provision of some information is mandatory: if relevant information is not provided, then we will not be able to administer a BiteTheBytes account to you, or provide you with the websites, apps, products or services requested. All other provision of your information is optional. Providing optional information will help us offer you a better experience, such as more personalized or tailored content or offerings.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">If you order us to delete your personal information that is required for the use of BiteTheBytes applications, products or services, you have no right to a refund of the purchase price.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">10. Online-Marketing practices of BiteTheBytes</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">BiteTheBytes uses various types of online advertising, including BiteTheBytes ads on websites and other business applications, as well as on social media platforms such as Facebook, YouTube, Twitter, Instagram, Vimeo, Twitch, and Discord. We do not operate direct marketing by email, telephone and post. BiteTheBytes does not send emails to unknown people to promote products.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">11. Sites of BiteTheBytes in social networks and login services</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">You can log in to some BiteTheBytes websites through an account on a social network such as Facebook. If you grant the appropriate permissions, we will receive information about you from your social network account, such as your name, location, and basic demographic information.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">BiteTheBytes runs its own pages on many social networking sites (eg. the Facebook page of the World Creator Team). We collect information that you have made public in your social network account, such as the name of our products and services that you are interested in when interacting with our social networking sites.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">12. Cookies</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Cookies are small text files stored by your web browser when you use websites. You can control how websites use cookies by configuring your browser's privacy settings (please refer to your browser's help function to learn more about cookie controls). Note that if you disable cookies entirely, BiteTheBytes websites may not function properly.</p>
                    <p class="font-weight-normal text-4 mb-2">BiteTheBytes and the companies that help us run our business use cookies in several ways, such as:</p>

                    <ul>
                        <li>Authenticating and identifying you on our websites so we can provide you the services you requested</li>
                        <li>Keeping track of information you have provided to us — for example, keeping items in your shopping cart</li>
                        <li>to make the website user-friendly and to optimally match your needs</li>
                    </ul>

                    <p class="font-weight-normal text-4 mb-2 text-justify">Session cookies are only used for the session. These cookies will be displayed after the session has ended, or deleted after leaving our website or closing the browser window.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Other cookies remain on your device for a longer period of time and allow us or third parties to recognize your browser on your next visit (persistent cookies).</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">13. Newsletter</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">BiteTheBytes does not offer a newsletter service at all.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">14. YouTube</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">You can watch some YouTube videos on our website. YouTube is a service of YouTube LLC, 901 Cherry Ave., San Bruno, CA 94066, USA. The company is affiliated with Google LLC, 1600 Amphitheater Parkway, Mountain View, CA 94043, USA.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">In order to prevent data from being transmitted to YouTube when the website in which the video is embedded is launched, we embedded the videos in the extended data protection mode. This will not send data to YouTube until you enable video playback by tapping or clicking on the video.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">To play the video, data such as the IP address of the computer you are using will be sent to YouTube. It also connects to ad network DoubleClick, a subsidiary of Google LLC. Cookies are set here. These are small text files that are stored and saved by the browser on your computer when visiting a website. The purpose of cookies is to provide advertising that is relevant to users, to improve campaign performance reports, or to prevent a user from seeing the same ads multiple times.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">With the videos we want to make our website more informative and entertaining for you. We have embedded the videos on our website to allow you to easily and quickly play the videos and make our website more user-friendly. The legal basis is Art. 6 (1) sentence 1 f DSGVO. The embedding of the YouTube videos for the aforementioned purposes represents our legitimate interest within the meaning of the GDPR.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">You can prevent the storage of cookies by a corresponding setting of your browser software. You can enable or disable Google's personalized advertising through the Advertising settings. If you opt out of personalized advertising, you'll still see ads, but the ads are no longer tailored to your interests. Instructions for deactivation can be found here.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Alternatively, you can install a browser plug-in to disable personalized advertising. This sets an opt-out cookie that prevents the DoubleClick cookie and disables interest-based advertising. The browser plug-in can be downloaded here.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Google LLC. is certified under the EU-US Privacy Shield, an agreement that ensures compliance with EU data protection rules. The privacy policy of Google can be found here.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">15. Vimeo</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Plug-ins of the Vimeo video portal of Vimeo, LLC, 555 West 18th Street, New York, New York 10011, USA are included on our websites. Each time you visit a page that offers one or more Vimeo video clips, a direct connection is established between your browser and a Vimeo server in the United States. This information about your visit and your IP address are stored there. Through interactions with the Vimeo plugins (for example, clicking the Start button), this information is also transmitted to Vimeo and stored there.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">In order to prevent a direct connection with Vimeo, all our videos that are located on Vimeo servers, are embedded in pop-up windows which requires you to actively open by clicking or tapping the appropriate images on our websites. However, if you do so, your personal data, such as your IP address is transmitted to Vimeo.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">If you have a Vimeo user account and do not want Vimeo to collect data about you through this website and link it to your member data stored with Vimeo, you must log out of Vimeo before visiting this website.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">The privacy policy for Vimeo with more detailed information on the collection and use of your data by Vimeo can be found at https://vimeo.com/privacy.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">In addition, Vimeo calls the Google Analytics tracker via an iframe that calls the video. This is a separate tracking of Vimeo, to which we have no access. You can stop Google Analytics tracking by using the opt-out tools that Google offers for some Internet browsers. Users may also prevent the collection by Google of the data generated by Google Analytics and related to their use of the website (including your IP address) and the processing of this data by Google by using the browser plug-in available at the following link Download and install: https://tools.google.com/dlpage/gaoptout.</p>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Some of our websites contain so-called embeddings of videos on Vimeo or videos from the Vimeo channels we operate. However, these only allow the connection to Vimeo. If you would like to receive information about the purpose and extent of the data collection and use by Vimeo, as well as your rights and options for protection as a Vimeo customer, please refer to the privacy notices of Vimeo (https://vimeo.com/privacy).</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">16. How long does BiteTheBytes retain my information?</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">If you purchased a product of BiteTheBytes based on perpetual use, we process and keep the personal information we have about you for as long as you are a user of our products, services or apps. If you purchased a product of BiteTheBytes based on rental use and you do not extend the rental period, we will immediately delete your personal information after your rental period has ended. If you ask us for a refund and we grant it, we will immediately delete your personal information after refund was processed.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">17. Will this privacy policy change?</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">Occasionally, we may change this privacy policy (or other documents in the BiteTheBytes Privacy Center) to allow BiteTheBytes to use or share your personal information in a different way. If we do, the links to the policy on our websites (which are generally found in the footer of the website) will indicate that the policy has been changed. For new users, the change will become effective upon posting. For existing users, if the change is significant, it will become effective 30 days after posting. We encourage you to periodically review the BiteTheBytes Privacy Center for the latest information on our privacy practices.</p>

                    <div class="font-weight-bold text-color-light line-height-2 text-8 mb-3 mt-5">18. Who can I contact with questions or concerns?</div>
                    <p class="font-weight-normal text-4 mb-2 text-justify">BiteTheBytes has appointed a Data Protection Officer. If you believe your Personal Information has been used in a way that is not consistent with this Policy or your specified preferences, or if you have further questions related to this policy, please contact the Data Protection Officer by writing an email to support@bitethebytes.com.</p>

                    <p class="font-weight-normal text-4 mb-4 mt-5">Written inquiries may be addressed to:</p>

                    <p class="font-weight-normal text-4 mb-2">BiteTheBytes GmbH</p>
                    <p class="font-weight-normal text-4 mb-2">Data Protection Officer</p>
                    <p class="font-weight-normal text-4 mb-2">Mainzer Str. 9</p>
                    <p class="font-weight-normal text-4 mb-2">36039 Fulda</p>
                    <p class="font-weight-normal text-4 mb-2">Germany</p>


                </div>
            </div>
        </div>
    </div>

    <footer id="footer" class="bg-color-dark-scale-5">
        <?php
        include 'php/footer.php';
        ?>
    </footer>
</div>
<!-- Vendor -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="../vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="../vendor/jquery.cookie/jquery.cookie.min.js"></script>
<script src="../vendor/popper/umd/popper.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../vendor/jquery.validation/jquery.validate.min.js"></script>
<script src="../vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="../vendor/jquery.gmap/jquery.gmap.min.js"></script>
<script src="../vendor/lazysizes/lazysizes.min.js"></script>
<script src="../vendor/isotope/jquery.isotope.min.js"></script>
<script src="../vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="../vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="../vendor/vide/jquery.vide.min.js"></script>
<script src="../vendor/vivus/vivus.min.js"></script>
<script src="../vendor/twentytwenty/js/jquery.event.move.js"></script>
<script src="../vendor/twentytwenty/js/jquery.twentytwenty.js"></script>

<!-- Current Page Vendor and Views -->
<script src="../vendor/circle-flip-slideshow/js/jquery.flipshow.min.js"></script>
<script src="../js/views/view.home.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="../js/theme.js"></script>

<!-- Theme Custom -->
<script src="../js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="../js/theme.init.js"></script>

<!-- Examples -->
<script src="../js/examples/examples.lightboxes.js"></script>
</body>
</html>