<?php

session_start();

include_once '../php/portal/portal.php';

\Portal\Maintenance::handle();

?>
<!DOCTYPE html>
<html class="dark bg-color-dark-scale-5"
      lang="en">
<head>
    <?php
    \Portal\Utility::writeMetaData('', '','');
    ?>

    <!-- Favicon -->
    <link rel="shortcut icon"
          href="../img/favicon.ico"
          type="image/x-icon"/>
    <link rel="apple-touch-icon"
          href="../img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link id="googleFonts"
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light%7CPlayfair+Display:400&display=swap"
          rel="stylesheet"
          type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet"
          href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="../vendor/fontawesome-pro-6.3.0-web/css/all.min.css">
    <link rel="stylesheet"
          href="../vendor/animate/animate.compat.css">
    <link rel="stylesheet"
          href="../vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet"
          href="../vendor/magnific-popup/magnific-popup.min.css">
    <link rel="stylesheet"
          href="../vendor/twentytwenty/css/twentytwenty.css">

    <!-- Theme CSS -->
    <link rel="stylesheet"
          href="../css/theme.css">
    <link rel="stylesheet"
          href="../css/theme-elements.css">
    <link rel="stylesheet"
          href="../css/theme-blog.css">
    <link rel="stylesheet"
          href="../css/theme-shop.css">

    <!-- Current Page CSS -->
    <link rel="stylesheet"
          href="../vendor/circle-flip-slideshow/css/component.css">

    <!-- Skin CSS -->
    <link id="skinCSS"
          rel="stylesheet"
          href="../css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet"
          href="../css/custom.css">

    <!-- Head Libs -->
    <script src="../vendor/modernizr/modernizr.min.js"></script>

    <script>
        window.fwSettings = {
            'widget_id': 44000002580
        };
        !function ()
        {
            if ("function" != typeof window.FreshworksWidget)
            {
                var n = function ()
                {
                    n.q.push(arguments)
                };
                n.q = [], window.FreshworksWidget = n
            }
        }()

        window.onload = function ()
        {
            OpenInformation();
        };

        function OpenInformation()
        {
            var shown = sessionStorage.getItem('alreadyShow');

            if (shown != "shown")
            {
                $("#info-window").modal('show');
                sessionStorage.setItem('alreadyShow', 'shown');
            }
        }
    </script>
    <script type="text/javascript"
            src="https://widget.freshworks.com/widgets/44000002580.js"
            async=""
            defer=""></script>

</head>

<body class="loading-overlay-showing"
      data-loading-overlay
      data-plugin-options="{'hideDelay': 500, 'effect': 'percentageProgress1'}">
<div class="loading-overlay loading-overlay-percentage bg-color-dark-scale-5">
    <div class="page-loader-progress-wrapper">
        <span class="page-loader-progress text-color-light">0</span>
        <span class="page-loader-progress-symbol text-color-light">%</span>
    </div>
</div>

<?php
include 'php/gdpr.php';
?>

<div class="body bg-color-dark-scale-5">
    <?php
    include 'php/header.php';
    ?>

    <div role="main" class="main">

        <?php

        if(!isset($_SERVER['HTTP_USER_AGENT']))
        {
            echo '<section class="section border-0 m-0" data-video-path="video/Trailer_01.mp4" data-plugin-video-background style="height: 100vh">';
        } else
        {
            $browserName = \Portal\Utility::getBrowser($_SERVER['HTTP_USER_AGENT']);

            if($browserName == 'Safari')
            {
                echo '
                        <section class="section border-0 m-0"
                                 style="background-image: url(../img/pages/World-Creator-01.webp); 
                                 background-size: cover; 
                                 background-position: center; 
                                 height: 100vh;">';
            } else
            {
                echo '
                        <section class="video section border-0 m-0"
                                 data-video-path="video/Trailer_01.mp4"
                                 data-plugin-video-background                                 
                                 style="height: 100vh">';
            }
        }

        ?>

        <div class="container text-center z-index-1 h-100">
            <div class="d-flex flex-column align-items-center justify-content-center h-100">
                <p class="text-12 line-height-1 font-weight-medium text-color-light appear-animation"
                   data-appear-animation="fadeInDownShorter"
                   data-plugin-options="{'minWindowWidth': 0}">TERRAIN AND LANDSCAPE CREATION</p>
                <p class="text-15 mb-5 line-height-1 font-weight-extra-bold text-color-light appear-animation"
                   data-appear-animation="blurIn"
                   data-plugin-options="{'minWindowWidth': 0}"
                   data-appear-animation-delay="300">LIGHT YEARS AHEAD</p>
                <p class="text-10 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                   data-appear-animation="blurIn"
                   data-plugin-options="{'minWindowWidth': 0}"
                   data-appear-animation-delay="500">Everything is real time. Everything? Everything!</p>
                <a href="buy.phtml"
                   class="btn btn-rounded btn-primary btn-modern font-weight-bold text-3 py-3 btn-px-5 mt-2 appear-animation"
                   data-appear-animation="fadeInUpShorter"
                   data-appear-animation-delay="700"
                   data-appear-animation-duration="1.2s"
                   data-plugin-options="{'minWindowWidth': 0}">GET CREATIVE NOW</a>
            </div>
            <a href="#main"
               class="slider-scroll-button slider-scroll-button-light position-absolute bottom-10 left-50pct transform3dx-n50"
               data-hash
               data-hash-offset="67"></a>
        </div>

        <?php
        echo '</section>';
        ?>

        <div id="main" class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://2k.com/en-US/" target="_blank"><img class="img-fluid"
                                                                     src="../img/logos/companies/2k.webp"
                                                                     alt="2K"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.a52.com/" target="_blank"><img class="img-fluid"
                                                                    src="../img/logos/companies/a52.webp"
                                                                    alt="a52"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://atlus.com/" target="_blank"><img class="img-fluid"
                                                                  src="../img/logos/companies/atlus.webp"
                                                                  alt="Atlus"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://avalanchestudios.com/" target="_blank"><img class="img-fluid"
                                                                             src="../img/logos/companies/avalanchestudio.webp"
                                                                             alt="Avalanche Studios"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://de.bandainamcoent.eu/" target="_blank"><img class="img-fluid"
                                                                             src="../img/logos/companies/bandainamco.webp"
                                                                             alt="Bandai Namco"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.bioware.com/" target="_blank"><img class="img-fluid"
                                                                        src="../img/logos/companies/bioware.webp"
                                                                        alt="Bioware"/></a>
            </div>
        </div>

        <div class="container bg-color-dark-scale-5 pt-5">
            <div class="row text-center pt-5">
                <div class="col p-0 appear-animation pt-5" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <h1 class="text-transform-none text-12 font-weight-bold line-height-2 pt-5">WELCOME TO THE NEXT GENERATION OF<br>TERRAIN AND LANDSCAPE CREATION</h1>
                </div>
            </div>
                <div class="row text-center pt-2">
                <div class="col p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <p class="text-5 line-height-4 font-weight-semi-bold"><b class="text-color-light">Watch the video below</b> and witness the incredible power of World Creator in a professional workflow! You won't believe what you can achieve with this amazing tool.</p>
                </div>
            </div>
        </div>

        <div class="embed-responsive embed-responsive-16by9">
            <iframe src="https://player.vimeo.com/video/925507071?h=ba6f0c6d5d" allow="autoplay; fullscreen" allowfullscreen></iframe>
        </div>

        <div class="container bg-color-dark-scale-5 pb-5">
            <div class="row text-center">
                <div class="col p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <h1 class="text-transform-none text-12 font-weight-bold line-height-2">THE ELITE REAL-TIME TERRAIN AUTHORING TOOL</h1>

                </div>
            </div>
            <div class="row text-justify pt-2 pb-5">
                <div class="col p-0 appear-animation pb-5" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <p class="text-5 line-height-4 font-weight-semi-bold pb-5">With its unparalleled power and precision, World Creator is the go-to software for the video game, simulation, and visual effects industries. Experience the most detailed and realistic terrain generation available today!
                        World Creator is the ultimate tool for generating and designing stunning 3D terrains, landscapes, and environments in real-time.
                </div>
            </div>
        </div>

        <!-- ********************************************************************************************** -->
        <!-- ********************************* THE ULTIMATE TERRAIN TOOL ********************************** -->
        <!-- ********************************************************************************************** -->
        <div class="row pt-5 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://www.blizzard.com/de-de/" target="_blank"><img class="img-fluid"
                                                               src="../img/logos/companies/blizzard.webp"
                                                               alt="Blizzard"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://bluebyte.ubisoft.com/de/" target="_blank"><img class="img-fluid"
                                                                src="../img/logos/companies/bluebyte.webp"
                                                                alt="BlueByte"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.blur.com/" target="_blank"><img class="img-fluid"
                                                     src="../img/logos/companies/blur.webp"
                                                     alt="Blur"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.bluepointgames.com/" target="_blank"><img class="img-fluid"
                                                               src="../img/logos/companies/bluepoint.webp"
                                                               alt="Blue Point Games"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.bossastudios.com/" target="_blank"><img class="img-fluid"
                                                             src="../img/logos/companies/bossastudios.webp"
                                                             alt="Bossa Studio"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.capcom.com/" target="_blank"><img class="img-fluid"
                                                       src="../img/logos/companies/capcom.webp"
                                                       alt="Capcom"/></a>
            </div>
        </div>
        <section class="section section-height-4 match-height border-top-0 my-0 section-center" style="background-image: url(../img/pages/World-Creator-03.webp); min-height: 1000px;">
            <div class="row text-center h-100 mx-0">
                <div class="col">
                    <h1 class="text-color-light line-height-2 font-weight-extra-bold text-14 mb-3">
                        THE ULTIMATE TERRAIN TOOL</h1>
                    <h2 class="text-color-light lead tall text-9">
                        NOTHING COMES CLOSE</h2>
                    <p class="text-5 text-color-light line-height-4 font-weight-semi-bold mb-4">World Creator is not just different, it's revolutionary! With no limits to your creativity, it's an absolute blast to use and explore.</p>
                </div>
            </div>
        </section>
        <div class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://www.certainaffinity.com/" target="_blank"><img class="img-fluid"
                                                                src="../img/logos/companies/certain_affinity.webp"
                                                                alt="Certain Affinity"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.cinesite.com/" target="_blank"><img class="img-fluid"
                                                         src="../img/logos/companies/cinesite.webp"
                                                         alt="Cinesite"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.codemasters.com/" target="_blank"><img class="img-fluid"
                                                            src="../img/logos/companies/codemasters.webp"
                                                            alt="Codemasters"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.crytek.com/" target="_blank"><img class="img-fluid"
                                                       src="../img/logos/companies/crytek.webp"
                                                       alt="Crytek"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://cyborn.be/" target="_blank"><img class="img-fluid"
                                                  src="../img/logos/companies/cyborn.webp"
                                                  alt="Cyborn"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.cygames.co.jp/en/" target="_blank"><img class="img-fluid"
                                                             src="../img/logos/companies/cygames.webp"
                                                             alt="Cygames"/></a>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">TERRAINS OF ANY SIZE</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">With World Creator, you can create terrains of any size, without any limits! Whether you want to create a small terrain of just a few meters or a massive one spanning thousands of kilometers, squared or non-squared, the possibilities are endless.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925029210?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">72 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/04.webp">
                    <p class="pl-3 pt-2 text-4 text-color-white float-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/16.webp">
                    <p class="pr-lg-3 pl-sm-3 pt-2 text-4 text-color-white float-lg-right float-sm-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
                <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">TERRAINS WITH UNLIMITED DETAIL</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">With our new and innovative terrain system, you can create terrains with an unlimited amount of detail! You can achieve meter precision, centimeter precision, and even more.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/854616459?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">166 Seconds - New video is in the works due to new website</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">BIOME-BASED WORKFLOW</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">With World Creator, you can create worlds that are limited only by your imagination!These worlds are made up of multiple terrain and landscape styles, known as biomes, which seamlessly blend into one another, each with its own unique color and filter settings. Thanks to World Creator's new terrain system, you can efficiently handle large amounts of data in real time, opening up a whole new world of possibilities, including biome-based generation, biome painting, biome masking, and much more.</p>
                                <br>
                                <div class="feature-box align-items-center">
                                    <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                        <i class="fas fa-play text-1"></i>
                                    </div>
                                    <div class="feature-box-info">
                                        <h4 class="line-height-3 text-3 mb-0">Showcase video in the works</h4>
                                        <p class="text-2 mb-0 line-height-5">Due to new website</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 400px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/29.webp">
                    <p class="pl-3 pt-2 text-4 text-color-white float-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/19.webp">
                    <p class="pr-lg-3 pl-sm-3 pt-2 text-4 text-color-white float-lg-right float-sm-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
                <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">NON-DESTRUCTIVE</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">With World Creator's unique workflow, you can confidently craft terrains using both design and procedural techniques. The possibilities are endless, and the rest of the terrain will conform to your vision with ease.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925446764?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">54 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>


        <!-- ********************************************************************************************** -->
        <!-- ********************************** PROCEDURAL MEETS DESIGN *********************************** -->
        <!-- ********************************************************************************************** -->
        <div class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://www.daybreakgames.com/home"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/daybreakgames.webp"
                                        alt="Daybreak Games"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.deck13.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/deck13.webp"
                                        alt="Deck13"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.dice.se/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/dice.webp"
                                        alt="DICE"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.digicpictures.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/digipic.webp"
                                        alt="Digipic"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.digitalextremes.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/digitalextremes.webp"
                                        alt="Digital Extremes"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.dlr.de/dlr/desktopdefault.aspx/tabid-10002/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/dlr.webp"
                                        alt="DLR"/></a>
            </div>
        </div>
        <section class="section section-height-4 match-height border-top-0 my-0 section-center" style="background-image: url(../img/pages/World-Creator-09.webp); min-height: 1000px;">
            <div class="row text-center h-100 mx-0">
                <div class="col">
                    <h1 class="text-color-light line-height-2 font-weight-extra-bold text-14 mb-3">
                        PROCEDURAL MEETS DESIGN</h1>
                    <h2 class="text-color-light lead tall text-9">
                        A TOUCH OF GENIUS</h2>
                    <p class="text-5 text-color-light line-height-4 font-weight-semi-bold mb-4">With World Creator, you can confidently and enthusiastically perfect the combination of a procedural and design workflow<br>to create the exact terrain you desire!</p>
                </div>
            </div>
        </section>
        <div class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://eidosmontreal.com/en"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/eidos_montreal.webp"
                                        alt="Eidos Montreal"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://falconscreativegroup.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/falconscreativegroup.webp"
                                        alt="Falcons Creative Group"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://firaxis.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/firaxis.webp"
                                        alt="Firaxis"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://firesprite.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/firesprite.webp"
                                        alt="Firesprite"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.frimastudio.com/en/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/frima.webp"
                                        alt="FRIMA"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.funcom.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/funcom.webp"
                                        alt="Funcom"/></a>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">RIVERS</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">Creating realistic rivers in World Creator is incredibly easy and efficient. With just one click, our system automates the river creation process and gives you full control to re-design it as you see fit. The terrain will adapt automatically, allowing you to create stunning waterfalls, river deltas, and everything in between. Whether you need small streams or large, complex river structures, World Creator has got you covered.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925814957?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">143 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/30.webp">
                    <p class="pl-3 pt-2 text-4 text-color-white float-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/08.webp">
                    <p class="pr-lg-3 pl-sm-3 pt-2 text-4 text-color-white float-lg-right float-sm-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
                 <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">ADVANCED SCULPTING</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">With World Creator, you can confidently create stunning terrains from scratch or modify existing landscapes with ease using the built-in sculpting tools. The application comes equipped with a wide range of brushes, and you can even import your own custom brushes to make your creations truly unique. The intuitive interface makes it as easy to use as any well-known paint application, so you can get started right away.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925058719?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">140 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">GRID-BASED SCULPTING</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">With our exceptional grid-based terrain sculpting algorithm, you can effortlessly create breathtaking terrain shapes in no time! Not only that, but you can also perform specific operations on existing terrain features, such as copying, rotating, tilting, and scaling.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925358252?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">99 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/09.webp">
                    <p class="pl-3 pt-2 text-4 text-color-white float-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/11.webp">
                    <p class="pr-lg-3 pl-sm-3 pt-2 text-4 text-color-white float-lg-right float-sm-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
                <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">TERRAIN STAMPING</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">With World Creator, you can easily import custom height, depth, displacement, and color maps as a stamp to create and extend your existing terrains or even create ground textures from scratch! Not only that, but you can also import DEM data or terrains from other applications and assemble a new landscape inside World Creator in real-time. Experience the power of creating your own world with World Creator!</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/854599230?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">169 Seconds - New video is in the works due to new website</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">PROCEDURAL STAMPING</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">We are thrilled to announce the addition of Procedural Stamps to our Terrain Stamping feature! With stamps for Volcanos, Islands, Cracks, and more, you can now save valuable time creating specific terrain features. It's like having a terrain generator right inside World Creator, allowing you to easily create stamps for any terrain type or feature you need.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925363250?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">150 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/12.webp">
                    <p class="pl-3 pt-2 text-4 text-color-white float-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/15.webp">
                    <p class="pr-lg-3 pl-sm-3 pt-2 text-4 text-color-white float-lg-right float-sm-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
                <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">PATH TOOLS</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">Our vector-based and distance-field-based path tools allow you to create rivers, roads, mountain ranges, canyons, and more, giving you unparalleled creative freedom.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925519721?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">145 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">REAL-WORLD DATA STREAMING</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">Sign up at <a href="https://www.maptiler.com" target="_blank">MapTiler</a> and connect to their real-world data service through World Creator to effortlessly import the locations of your choice! With World Creator, utilizing real-world data for your productions is a breeze. Remember, you must sign up on MapTiler to use the service.</p>
                                <div class="row">
                                    <div class="col-6">
                                        <br>
                                        <a class="text-decoration-none lightbox"
                                           href="https://vimeo.com/925321330?share=copy"
                                           data-plugin-options="{'type':'iframe'}">
                                            <div class="feature-box align-items-center">
                                                <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                                    <i class="fas fa-play text-1"></i>
                                                </div>
                                                <div class="feature-box-info">
                                                    <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                                    <p class="text-2 mb-0 line-height-5">129 Seconds</p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="col-6 float-right">
                                        <p class="mt-4">
                                            <a href="https://www.maptiler.com" target="_blank">
                                                <img src="../img/logos/companies/Maptiler-Logo-Grey.webp" alt="MapTiler Logo">
                                            </a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/13.webp">
                    <p class="pl-3 pt-2 text-4 text-color-white float-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/22.webp">
                        <p class="pr-lg-3 pl-sm-3 pt-2 text-4 text-color-white float-lg-right float-sm-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                    </div>
                <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">PROCEDURAL FILTER POWER</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">In World Creator, procedural filters are expertly applied to transform a terrain shape into a variety of stunning landscapes. Whether you're looking to create deserts, snowy mountains, arid canyons, volcano islands, wet highlands, Moon-like cratered landscapes or Mars-like worlds, our filters have got you covered. With the ability to apply erosions and sediments, you can easily style your terrain to achieve the perfect look in no time at all.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925440545?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">61 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">PROCEDURAL MATERIAL POWER</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-5">World Creator has an incredibly compelling material system! You can define colors, gradients, sat-maps, textures, and Adobe Substance materials to color every single terrain feature. Whether you want simple colors to quickly tint your terrain, or textures and Adobe Substance materials to make it look fantastic, or gradients and sat-maps to take the coloring process to the highest possible level, World Creator has got you covered. With its real-time rendering, you can create outstanding landscapes that will leave you in awe!</p>
                                <div class="row">
                                    <div class="col-6">
                                        <br>
                                        <div class="feature-box align-items-center">
                                            <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                                <i class="fas fa-play text-1"></i>
                                            </div>
                                            <div class="feature-box-info">
                                                <h4 class="line-height-3 text-3 mb-0">Showcase video in the works</h4>
                                                <p class="text-2 mb-0 line-height-5">Due to new website</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-6 float-right">
                                        <p class="mt-4">
                                            <a href="https://www.adobe.com" target="_blank">
                                                <img src="../img/logos/companies/Adobe-Logo-Grey.webp" alt="Adobe Logo">
                                            </a>
                                        </p>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </section>
                </div>
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 0.0}" data-image-src="../img/pages/32.webp">
                    <p class="pl-3 pt-2 text-4 text-color-white float-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
            </div>
        </div>


        <!-- ********************************************************************************************** -->
        <!-- ********************************* DRIVE POWERFUL SIMULATIONS ********************************* -->
        <!-- ********************************************************************************************** -->
        <div class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://www.ghostvfx.com"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/ghost_vfx.webp"
                                        alt="GHOST VFX"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://hotheadgames.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/hotheadstudio.webp"
                                        alt="Hothead Studio"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://hybride.com/en"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/hybride.webp"
                                        alt="Hybride"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://improbable.io/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/improbable.webp"
                                        alt="Improbable"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://corp.joycity.com"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/joycity.webp"
                                        alt="Joy City"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.kylotonn.com/en/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/ktracing.webp"
                                        alt="KT Racing"/></a>
            </div>
        </div>
        <section class="section section-height-4 match-height border-top-0 my-0 section-center" style="background-image: url(../img/pages/World-Creator-08.webp); min-height: 1000px;">
            <div class="row text-center h-100 mx-0">
                <div class="col">
                    <h1 class="text-color-light line-height-2 font-weight-extra-bold text-14 mb-3">
                        DRIVE POWERFUL SIMULATIONS</h1>
                    <h2 class="text-color-light lead tall text-9">
                        REAL TERRAIN PHYSICS</h2>
                    <p class="text-5 text-color-light line-height-4 font-weight-semi-bold mb-4">With our Simulation Layers, you can confidently run multiple physics simulations simultaneously! Experience the power of our technology today.</p>
                </div>
            </div>
        </section>
        <div class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://www.limbic-entertainment.de/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/limbic.webp"
                                        alt="Limbic"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.liongamelion.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/liongamelion.webp"
                                        alt="Lion Game Lion"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://mawiunited.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/mawi.webp"
                                        alt="MAWI"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.microsoftstudios.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/microsoft.webp"
                                        alt="Microsoft"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://us.ncsoft.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/ncsoft.webp"
                                        alt="NC Soft"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://neocoregames.com/en"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/neocoregames.webp"
                                        alt="Neocoregames"/></a>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/23.webp">
                    <p class="pr-lg-3 pl-sm-3 pt-2 text-4 text-color-white float-lg-right float-sm-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
                <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">SAND</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">Creating a Simulation Layer and choosing the type of simulation, such as sand, is all it takes to get started. With the option to use brushes or procedural techniques, you can easily drop an adjustable amount of sand on the terrain and watch it distribute. Our user-friendly approach makes complexity accessible to everyone.</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925341914?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">99 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">SNOW</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">With World Creator, you can confidently simulate snow on top of your terrain!The workflow is just as easy as the sand simulation (see above), but the outcome is uniquely different based on your simulation settings. You can even define specific regions where you want snow to appear - it's that simple!</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925429996?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">61 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/24.webp">
                    <p class="pl-3 pt-2 text-4 text-color-white float-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="parallax order-lg-1 order-1 col-lg-6 match-height p-0" style="min-height: 700px;" data-plugin-parallax data-plugin-options="{'speed': 1.5}" data-image-src="../img/pages/33.webp">
                    <p class="pr-lg-3 pl-sm-3 pt-2 text-4 text-color-white float-lg-right float-sm-left alternative-font appear-animation" data-appear-animation="fadeIn" data-appear-animation-delay="200">Rendered within World Creator</p>
                </div>
                <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">FLUID</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-4">The fluid simulation is an incredibly versatile tool that can be used to fill rivers, lakes, and seas with water, as well as create lava and other types of fluid interactions. By defining specific locations for fluid spawning (as shown in the image), World Creator takes care of the rest. The possibilities are truly limitless!</p>
                                <br>
                                <a class="text-decoration-none lightbox"
                                   href="https://vimeo.com/925354920?share=copy"
                                   data-plugin-options="{'type':'iframe'}">
                                    <div class="feature-box align-items-center">
                                        <div class="feature-box-icon pulseAnim pulseAnimAnimated">
                                            <i class="fas fa-play text-1"></i>
                                        </div>
                                        <div class="feature-box-info">
                                            <h4 class="line-height-3 text-3 mb-0">Watch video</h4>
                                            <p class="text-2 mb-0 line-height-5">100 Seconds</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <!-- ********************************************************************************************** -->
        <!-- ********************************** UNIVERSAL COMPATIBILITY *********************************** -->
        <!-- ********************************************************************************************** -->
        <div class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <img class="img-fluid"
                     src="../img/logos/companies/nexon.webp"
                     alt="Nexon"/>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.paradoxinteractive.com/en/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/paradox_interactive.webp"
                                        alt="Paradox Interactive"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.perfectworld.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/perfect_world.webp"
                                        alt="Perfect World"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.piranha-bytes.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/piranhabytes.webp"
                                        alt="Piranha Bytes"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.playground-games.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/playgroundgames.webp"
                                        alt="Playgroundgames"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://pocketgems.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/pocketgems.webp"
                                        alt="Pocket Gems"/></a>
            </div>
        </div>
        <section class="section section-height-4 match-height border-top-0 my-0 section-center" style="background-image: url(../img/pages/World-Creator-07.webp); min-height: 1000px;">
            <div class="row text-center h-100 mx-0">
                <div class="col">
                    <h1 class="text-color-light line-height-2 font-weight-extra-bold text-14 mb-3">
                        UNIVERSAL COMPATIBILITY</h1>
                    <h2 class="text-color-light lead tall text-9">
                        CONNECT TO ALMOST ANYTHING</h2>
                    <p class="text-5 text-color-light line-height-4 font-weight-semi-bold mb-4">Every professional 3D application out there consumes World Creator data with confidence!</p>
                </div>
            </div>
        </section>
        <div class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://www.quanticdream.com/en"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/quanticdream.webp"
                                        alt="Quantic Dream"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.rsvfx.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/rocketscience.webp"
                                        alt="Rocketscience"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.sae.edu/deu/de"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/sae.webp"
                                        alt="SAE"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.square-enix.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/squareenix.webp"
                                        alt="Square Eenix"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://styleframe.de/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/styleframe.webp"
                                        alt="Styleframe"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.sumo-digital.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/sumodigital.webp"
                                        alt="Sumo Digital"/></a>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-1 order-1 col-lg-6 match-height p-0">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col">
                            <div id="applications">
                                <div class="row mt-4 text-center">
                                    <div class="col-4">
                                        <a href="https://www.blender.org/"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/blender.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Blender">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Blender</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.maxon.net"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/cinema4d.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Cinema 4D">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Cinema 4D</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.sidefx.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/houdini.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Houdini">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Houdini</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://unity.com/"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/unity.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Unity Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Unity Engine</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.unrealengine.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/unreal.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Unreal Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Unreal Engine</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="order-lg-0 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">BRIDGE TOOLS</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-5">Our World Creator bridge tools / plugins are available for Blender, Cinema4D, SideFX Houdini, Unity, and Unreal. With just a single click, you can transfer a terrain from World Creator to any of these applications. Experience seamless integration and effortless workflow.</p>
                                <ul class="list list-icons list-icons-sm pt-2">
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> World Creator to Blender Bridge</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> World Creator to Cinema 4D Bridge</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> World Creator to Houdini Bridge</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> World Creator to Unity Bridge</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> World Creator to Unreal Bridge</li>
                                </ul>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row">
                <div class="order-lg-1 order-0 col-lg-6 p-0 appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                    <section class="section section-height-5 match-height border-top-0 my-0 bg-color-dark-scale-5">
                        <div class="row justify-content-center align-items-center h-100 mx-0">
                            <div class="col-lg-8">
                                <h3 class="text-transform-none text-12 font-weight-bold line-height-2 pb-4">FORMATS AND APPLICATIONS</h3>
                                <p class="text-5 line-height-4 font-weight-semi-bold mb-5">World Creator confidently supports exporting in a wide range of formats, including Collada, OBJ, FBX, GLTF2, STL, TIFF, PNG, RAW (16 or 32-bit), and EXR (32-bit), among others. This ensures that your assets can be loaded into any serious 3D DCC application or game engine, providing the broadest industry coverage possible. Get ready to take your creations to the next level with World Creator!</p>
                                <ul class="list list-icons list-icons-sm pt-2">
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> Height-Map export</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> Color-Map export</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> Splat-Map export</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> Normal-Map export</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> Roughness-Map export</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> Metalness-Map export</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> AO-Map export</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> Topo-Map export</li>
                                    <li class="text-5 font-weight-semi-bold line-height-4"><i class="fas fa-caret-right"></i> Mesh export</li>
                                </ul>
                            </div>
                        </div>
                    </section>
                </div>
                <div class="order-lg-0 order-1 col-lg-6 match-height pb-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col">
                            <div id="applications">
                                <div class="row mt-4 text-center">
                                    <div class="col-4">
                                        <a href="https://www.arnoldrenderer.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/arnold.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Arnold">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Arnold</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.blender.org/"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/blender.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Blender">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Blender</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.maxon.net"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/cinema4d.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Cinema 4D">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Cinema 4D</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.isotropix.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/clarisse.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Clarisse">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Clarisse</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.cryengine.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/cry.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Cry Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Cry Engine</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.daz3d.com/get_studio"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/dazstudio.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="DAZ Studio">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">DAZ Studio</p>
                                    </div>
                                </div>
                                <div class="row text-center">
                                    <div class="col-4">
                                        <a href="https://flaxengine.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/flax.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Flax Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Flax Engine</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://godotengine.org"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/godot.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Godot Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Godot Engine</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.sidefx.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/houdini.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Houdini">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Houdini</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.lightwave3d.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/lightwave.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Lightwave">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Lightwave</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://aws.amazon.com/de/lumberyard"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/lumberyard.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Lumberyard Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Lumberyard Engine</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.autodesk.de/products/3ds-max"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/3dsmax.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="3DS Max">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">3DS Max</p>
                                    </div>
                                </div>
                                <div class="row text-center">
                                    <div class="col-4">
                                        <a href="https://www.autodesk.de/products/maya"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/maya.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Maya">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Maya</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.autodesk.de/products/mudbox"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/mudbox.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="MudBox">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">MudBox</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://home.otoy.com/render/octane-render/"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/octane.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Octane">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Octane</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.adobe.com/products/photoshop.html"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/photoshop.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Photoshop">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Photoshop</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://quixel.com/mixer"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/quixelmixer.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Quixel Mixer">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Quixel Mixer</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.substance3d.com/"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/applications/substance3ddesigner.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Substance 3D Designer">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Substance 3D Designer</p>
                                    </div>
                                </div>
                                <div class="row text-center">
                                    <div class="col-4">
                                        <a href="https://unity.com/"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/unity.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Unity Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Unity Engine</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://unigine.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/unigine.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Unigine Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Unigine Engine</p>
                                    </div>
                                    <div class="col-4">
                                        <a href="https://www.unrealengine.com"
                                           target="_blank">
                                            <img class="img-fluid rounded-circle mb-4"
                                                 src="../img/logos/engines/unreal.webp"
                                                 width="64"
                                                 height="64"
                                                 alt="Unreal Engine">
                                        </a>
                                        <p class="font-weight-semi-bold text-color-white">Unreal Engine</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- ********************************************************************************************** -->
        <!-- ******************************** WORLD CREATOR IS FUN TO USE ********************************* -->
        <!-- ********************************************************************************************** -->
        <div class="row pt-3 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://www.take2games.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/take2gaming.webp"
                                        alt="Take2 Gaming"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.ttgames.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/telltalegames.webp"
                                        alt="Telltale Games"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://thqnordic.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/thqnordic.webp"
                                        alt="THQ Nordic"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.treyarch.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/treyarch.webp"
                                        alt="Treyarch"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.ubisoft.com/en-us"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/ubisoft.webp"
                                        alt="Ubisoft"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://unity.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/unity.webp"
                                        alt="Unity"/></a>
            </div>
        </div>
        <section class="section section-height-4 match-height border-top-0 my-0 section-center" style="background-image: url(../img/pages/World-Creator-04.webp); min-height: 1000px;">
            <div class="row text-center h-100 mx-0">
                <div class="col">
                    <h1 class="text-color-light line-height-2 font-weight-extra-bold text-14 mb-3">
                        WORLD CREATOR IS FUN TO USE</h1>
                    <h2 class="text-color-light lead tall text-9">
                        AND SO MUCH MORE</h2>
                    <p class="text-5 text-color-light line-height-4 font-weight-semi-bold mb-4">This powerful and ultra-fast tool is not only fun to use, but it also allows for limitless creativity.<br>Plus, its fantastic design is sure to impress!</p>
                </div>
            </div>
        </section>
        <div class="row pt-1 pb-1 bg-color-dark-scale-5">
            <div class="col-2 text-center">
                <a href="https://www.valvesoftware.com/de/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/valve.webp"
                                        alt="Valve"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://virtuosgames.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/virtuos.webp"
                                        alt="Virtuos"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.wbgames.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/wbgames.webp"
                                        alt="WB Games"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.weltenbauer-se.com"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/weltenbauer.webp"
                                        alt="Weltenbauer"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.xlgames.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/xlgames.webp"
                                        alt="XL Games"/></a>
            </div>
            <div class="col-2 text-center">
                <a href="https://www.zenimax.com/"
                   target="_blank"><img class="img-fluid"
                                        src="../img/logos/companies/zenimax.webp"
                                        alt="Zenimax"/></a>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row appear-animation pt-5" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">RAY-TRACED RENDERING</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">Every image on this page was rendered as-is within World Creator! That means what you see here is exactly the same as what you see while working with World Creator. We have implemented our own real-time ray-tracer that serves with amazing renders. Our technology is cutting-edge and we are proud to showcase it here.</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">HUGE MATERIAL LIBRARY</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">With World Creator, you gain access to an extensive material library of over 138 high-quality materials, readily available for use in Unity, Unreal, Adobe Substance, or any other application. Purchase World Creator today and elevate your creations with ease! These materials, originally created by RD-Textures, are now available to you royalty-free.</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">HUGE PRESET LIBRARY</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">With World Creator, you have the power to create presets for biomes, filters, materials, exports, brushes, and much more! Our extensive library of presets is designed to streamline your workflow and can be easily applied through simple drag-and-drop operations. Customize them to your liking and watch your creations come to life!</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row appear-animation" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">HUGE SAMPLE LIBRARY</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">We have created an extensive collection of terrain samples that you can use as a starting point for your own productions. These samples are also great for learning and will provide you with a solid introduction to working with World Creator. Additionally, you have the option to create your own samples and share them with the community.</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">EXTENSIVE DOCUMENTATION</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">World Creator's documentation is the perfect complement to our support system. By using the support widget located at the bottom right of the screen, you can easily find the help you need and be directed to the most relevant article. Additionally, World Creator offers a built-in help reference that provides a comprehensive explanation of any section you may be looking for. With these resources at your disposal, you can be confident in your ability to navigate and utilize World Creator to its fullest potential.</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">HUGE COMMUNITY</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">The World Creator Discord community has impressively grown to over 13,000 users worldwide! We're proud to have over 11,000 followers on Instagram too. This level of support is a testament to the helpful and friendly nature of our community. For the best experience, we recommend joining us on Discord where you can directly get in touch with us, the developers!</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row appear-animation pb-5" data-appear-animation="fadeInUpShorter" data-appear-animation-delay="200">
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">ZERO LEARNING CURVE</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">World Creator is incredibly easy to use! Built around simplicity, it is designed to be intuitive and lightning-fast for anyone who wants to create terrains. With World Creator, you can create stunning landscapes in just minutes while maintaining incredible control. Whether you're in a hurry or want to dive deep, World Creator has got you covered.</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">CLEAN UI</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">Forget nodes! Forget their complex wiring that looks like spaghetti! Forget multiple views and windows that just irritate you while working! World Creator's UI is clean, focused, and intuitive. You will feel immediately comfortable - we promise!</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 p-0 pt-5">
                    <div class="row justify-content-center align-items-center h-100 mx-0">
                        <div class="col-lg-8">
                            <h2 class="pl-2 pr-2 font-weight-semibold text-6">OUTSTANDING SUPPORT</h2>
                            <div data-plugin-readmore
                                 data-plugin-options="{
									'buttonOpenLabel': '<i class=\'fas fa-chevron-down text-4 ml-1\'></i>',
									'buttonCloseLabel': '<i class=\'fas fa-chevron-up text-4 ml-1\'></i>',
									'overlayColor': '#0f1112',
									'align': 'right',
									'enableToggle': false
								}">
                                <p class="pl-2 pr-2 line-height-4 text-5">Our support is not just a Facebook page - we have an excellent ticketing system that allows us to provide excellent 24/7 support. The support system is also linked to our documentation, so you can get quick solutions in no time.</p>
                                <div class="readmore-button-wrapper d-none pr-2">
                                    <a href="#" class="text-decoration-none text-color-grey">
                                        <i class="fas fa-chevron-down"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container-fluid bg-color-dark-scale-5">
            <div class="row text-center pt-5 pb-5">
                <div class="col p-0">
                    <h1 class="text-transform-none text-12 font-weight-bold line-height-2 pt-5">CHECK THE RENDERS BELOW</h1>
                    <p class="text-5 line-height-4 font-weight-semi-bold">This is what you see while working with World Creator</p>
                    <div class="row justify-content-center align-items-center">

                    </div>
                </div>
            </div>
        </div>


        <div class="lightbox" data-plugin-options="{'delegate': 'a', 'type': 'image', 'gallery': {'enabled': true}, 'mainClass': 'mfp-with-zoom', 'zoom': {'enabled': true, 'duration': 300}}">
            <div class="masonry-loader masonry-loader-showing">
                <div class="masonry"
                     data-plugin-masonry
                     data-plugin-options="{'itemSelector': '.masonry-item'}">
                    <?php
                    $files = \Portal\Utility::getAllFilesInDirectory('../img/renders');

                    foreach($files as $file)
                    {
                        if($file == "thumbs") continue;

                        echo '<div class="masonry-item">
                                    <div class="thumb-info-floating-caption thumb-info-hide-wrapper-bg" data-title="World Creator In-App Render">
                                        <a class="d-inline-block img-thumbnail img-thumbnail-no-borders mb-1 mr-1" href="../img/renders/' . $file . '">
                                          <img class="img-fluid" src="../img/renders/thumbs/' . $file . '" alt="World Creator Render"/>
                                        </a>
                                    </div>
                                  </div>';
                    }
                    ?>
                </div>
            </div>
        </div>

    </div>

    <footer id="footer" class="bg-color-dark-scale-5 mt-0 my-0">
        <?php
        include 'php/footer.php';
        ?>
    </footer>
</div>
<!-- Vendor -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="../vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="../vendor/jquery.cookie/jquery.cookie.min.js"></script>
<script src="../vendor/popper/umd/popper.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../vendor/jquery.validation/jquery.validate.min.js"></script>
<script src="../vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="../vendor/jquery.gmap/jquery.gmap.min.js"></script>
<script src="../vendor/lazysizes/lazysizes.min.js"></script>
<script src="../vendor/isotope/jquery.isotope.min.js"></script>
<script src="../vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="../vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="../vendor/vide/jquery.vide.min.js"></script>
<script src="../vendor/vivus/vivus.min.js"></script>
<script src="../vendor/twentytwenty/js/jquery.event.move.js"></script>
<script src="../vendor/twentytwenty/js/jquery.twentytwenty.js"></script>

<!-- Current Page Vendor and Views -->
<script src="../vendor/circle-flip-slideshow/js/jquery.flipshow.min.js"></script>
<script src="../js/views/view.home.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="../js/theme.js"></script>

<!-- Theme Custom -->
<script src="../js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="../js/theme.init.js"></script>

<!-- Examples -->
<script src="../js/examples/examples.lightboxes.js"></script>
</body>
</html>