<?php

session_start();

include_once '../php/portal/portal.php';

\Portal\Maintenance::handle();

?>
<!DOCTYPE html>
<html class="dark bg-color-dark-scale-5"
      lang="pt">
<head>
    <!-- Google tag (gtag.js) --> <script async src="https://www.googletagmanager.com/gtag/js?id=AW-1015744886 "></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-1015744886'); </script>

    <?php
    \Portal\Utility::writeMetaData('', '','','en');
    ?>

    <!-- Favicon -->
    <link rel="shortcut icon"
          href="../img/favicon.png"
          type="image/x-icon"/>
    <link rel="apple-touch-icon"
          href="../img/apple-touch-icon.png">

    <!-- Mobile Metas -->
    <meta name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

    <!-- Web Fonts  -->
    <link id="googleFonts"
          href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800%7CShadows+Into+Light%7CPlayfair+Display:400&display=swap"
          rel="stylesheet"
          type="text/css">

    <!-- Vendor CSS -->
    <link rel="stylesheet"
          href="../vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="../vendor/fontawesome-free/css/all.min.css">
    <link rel="stylesheet"
          href="../vendor/animate/animate.compat.css">
    <link rel="stylesheet"
          href="../vendor/simple-line-icons/css/simple-line-icons.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.carousel.min.css">
    <link rel="stylesheet"
          href="../vendor/owl.carousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet"
          href="../vendor/magnific-popup/magnific-popup.min.css">
    <link rel="stylesheet"
          href="../vendor/twentytwenty/css/twentytwenty.css">

    <!-- Theme CSS -->
    <link rel="stylesheet"
          href="../css/theme.css">
    <link rel="stylesheet"
          href="../css/theme-elements.css">
    <link rel="stylesheet"
          href="../css/theme-blog.css">
    <link rel="stylesheet"
          href="../css/theme-shop.css">

    <!-- Current Page CSS -->
    <link rel="stylesheet"
          href="../vendor/circle-flip-slideshow/css/component.css">

    <!-- Skin CSS -->
    <link id="skinCSS"
          rel="stylesheet"
          href="../css/skins/default.css">

    <!-- Theme Custom CSS -->
    <link rel="stylesheet"
          href="../css/custom.css">

    <!-- Head Libs -->
    <script src="../vendor/modernizr/modernizr.min.js"></script>

    <script type="text/javascript">
        window.onload = function ()
        {
            OpenInformation();
        };

        function OpenInformation()
        {
            var element = document.getElementById("info-window");

            if (element)
                $("#info-window").modal('show');
        }
    </script>

    <script>
        window.fwSettings = {
            'widget_id': 44000002580
        };
        !function ()
        {
            if ("function" != typeof window.FreshworksWidget)
            {
                var n = function ()
                {
                    n.q.push(arguments)
                };
                n.q = [], window.FreshworksWidget = n
            }
        }()
    </script>
    <script type="text/javascript"
            src="https://widget.freshworks.com/widgets/44000002580.js"
            async=""
            defer=""></script>

</head>

<body class="loading-overlay-showing"
      data-loading-overlay
      data-plugin-options="{'hideDelay': 500, 'effect': 'percentageProgress1'}">
<div class="loading-overlay loading-overlay-percentage bg-color-dark">
    <div class="page-loader-progress-wrapper">
        <span class="page-loader-progress text-color-light">0</span>
        <span class="page-loader-progress-symbol text-color-light">%</span>
    </div>
</div>

<?php
include 'php/gdpr.php';
?>

<div class="body bg-color-dark-scale-5">
    <?php
    include 'php/header.php';
    ?>

    <div role="main" class="main">
        <section class="section border-0 m-0 p-0"
                 style="background-image: url(../img/pages/World-Creator-01.webp); background-size: cover; background-position: center; height: 100vh;">
            <div class="container text-center z-index-1 h-100">
                    <?php
                    if(isset($_GET["ret"]))
                    {
                        echo '                    
                        <div class="d-flex flex-column align-items-center justify-content-center h-100">
                            <p class="text-15 mb-5 line-height-1 font-weight-extra-bold text-color-light appear-animation"
                               data-appear-animation="fadeInDownShorter"
                               data-plugin-options="{\'minWindowWidth\': 0}">THANK YOU</p>
                            <p class="text-6 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                               data-appear-animation="blurIn"
                               data-plugin-options="{\'minWindowWidth\': 0}"
                               data-appear-animation-delay="700">' . $_GET["ret"] . '</p>
                            <p class="text-6 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                               data-appear-animation="blurIn"
                               data-plugin-options="{\'minWindowWidth\': 0}"
                               data-appear-animation-delay="700">You may now <a href="buy.phtml">leave</a> this page</p>
                        </div>                    
                        ';
                    }
                    else if(isset($_GET["err"]))
                    {
                        echo '                    
                        <div class="d-flex flex-column align-items-center justify-content-center h-100">
                            <p class="text-15 mb-5 line-height-1 font-weight-extra-bold text-color-light appear-animation"
                               data-appear-animation="fadeInDownShorter"
                               data-plugin-options="{\'minWindowWidth\': 0}">OH SNAP</p>
                            <p class="text-8 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                               data-appear-animation="blurIn"
                               data-plugin-options="{\'minWindowWidth\': 0}"
                               data-appear-animation-delay="500">There was an issue with your request</p>
                            <p class="text-6 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                               data-appear-animation="blurIn"
                               data-plugin-options="{\'minWindowWidth\': 0}"
                               data-appear-animation-delay="700">' . $_GET["err"] . '</p>
                            <p class="text-6 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                               data-appear-animation="blurIn"
                               data-plugin-options="{\'minWindowWidth\': 0}"
                               data-appear-animation-delay="700">You may now <a href="buy.phtml">return</a> and try again</p>
                        </div>                    
                        ';
                    }
                    else
                    {
                        echo '                    
                        <div class="d-flex flex-column align-items-center justify-content-center h-100">
                            <p class="text-15 mb-5 line-height-1 font-weight-extra-bold text-color-light appear-animation"
                               data-appear-animation="fadeInDownShorter"
                               data-plugin-options="{\'minWindowWidth\': 0}">NOTHING TO CONFIRM</p>
                            <p class="text-6 mb-4 line-height-2 font-weight-bold text-color-light opacity-9 appear-animation"
                               data-appear-animation="blurIn"
                               data-plugin-options="{\'minWindowWidth\': 0}"
                               data-appear-animation-delay="700">You may <a href="index.phtml">leave</a> this page</p>
                        </div>                    
                        ';
                    }
                    ?>
            </div>
        </section>
    </div>
</div>

<!-- Vendor -->
<script src="../vendor/jquery/jquery.min.js"></script>
<script src="../vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="../vendor/jquery.easing/jquery.easing.min.js"></script>
<script src="../vendor/jquery.cookie/jquery.cookie.min.js"></script>
<script src="../vendor/popper/umd/popper.min.js"></script>
<script src="../vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="../vendor/jquery.validation/jquery.validate.min.js"></script>
<script src="../vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
<script src="../vendor/jquery.gmap/jquery.gmap.min.js"></script>
<script src="../vendor/lazysizes/lazysizes.min.js"></script>
<script src="../vendor/isotope/jquery.isotope.min.js"></script>
<script src="../vendor/owl.carousel/owl.carousel.min.js"></script>
<script src="../vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="../vendor/vide/jquery.vide.min.js"></script>
<script src="../vendor/vivus/vivus.min.js"></script>
<script src="../vendor/twentytwenty/js/jquery.event.move.js"></script>
<script src="../vendor/twentytwenty/js/jquery.twentytwenty.js"></script>

<!-- Current Page Vendor and Views -->
<script src="../vendor/circle-flip-slideshow/js/jquery.flipshow.min.js"></script>
<script src="../js/views/view.home.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="../js/theme.js"></script>

<!-- Theme Custom -->
<script src="../js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="../js/theme.init.js"></script>

<!-- Examples -->
<script src="../js/examples/examples.lightboxes.js"></script>
</body>
</html>